- README.md
- src/store/message-store-level.ts
- tests/dwn.spec.ts
- tests/interfaces/collections/handlers/collections-write.spec.ts
- tests/interfaces/collections/messages/collections-write.spec.ts
- tests/store/message-store.spec.ts
- tests/utils/test-data-generator.ts
1. Allowed all characters for indexing
2. Added regression test + test code refactoring
> issue #80 - Search index broken for non letter/digit characters

- .eslintrc.cjs
- README.md
- package-lock.json
- package.json
- src/core/message.ts
- src/index.ts
- src/interfaces/collections/messages/collections-write.ts
- src/interfaces/permissions/messages/permissions-grant.ts
- src/interfaces/permissions/messages/permissions-request.ts
- src/interfaces/protocols/handlers/protocols-configure.ts
- src/interfaces/protocols/handlers/protocols-query.ts
- src/interfaces/protocols/messages/protocols-configure.ts
- src/interfaces/protocols/messages/protocols-query.ts
- src/interfaces/protocols/types.ts
- src/jose/algorithms/signing/ed25519.ts
- src/jose/algorithms/signing/secp256k1.ts
- src/utils/object.ts
- src/validation/json-schemas/index.ts
- src/validation/json-schemas/protocol-definition.json
- src/validation/json-schemas/protocol-rule-set.json
- src/validation/json-schemas/protocols/protocols-configure.json
- src/validation/json-schemas/protocols/protocols-query.json
- tests/did/did-resolver.spec.ts
- tests/did/ion-did-resolver.spec.ts
- tests/interfaces/collections/handlers/collections-write.spec.ts
- tests/interfaces/protocols/handlers/protocols-query.spec.ts
- tests/jose/jws/general.spec.ts
- tests/utils/cid.spec.ts
- tests/utils/memory-cache.spec.ts
- tests/utils/test-data-generator.ts
Supports both  `ProtocolsConfigure` and `ProtocolsQuery`.
> added `protocols` interface support

- .eslintrc.cjs
- README.md
- package-lock.json
- package.json
- src/did/did-key-resolver.ts
- src/did/did-resolver.ts
- src/dwn.ts
- src/jose/algorithms/signing/ed25519.ts
- src/jose/algorithms/signing/secp256k1.ts
- src/jose/types.ts
- tests/did/did-key-resolver.spec.ts
- tests/dwn.spec.ts
- tests/jose/algorithms/signing/secp256k1.spec.ts
Added `did:key` support for ED25519 & SECP256K1 with 100% test code coverage
> added did:key support

- README.md
- package-lock.json
- src/core/auth.ts
- src/core/types.ts
- src/interfaces/collections/handlers/collections-query.ts
- src/interfaces/collections/handlers/collections-write.ts
- src/interfaces/collections/messages/collections-query.ts
- src/interfaces/collections/messages/collections-write.ts
- src/interfaces/permissions/handlers/permissions-request.ts
- src/interfaces/protocols/handlers/protocols-configure.ts
- src/store/message-store-level.ts
- src/store/message-store.ts
- tests/interfaces/collections/handlers/collections-query.spec.ts
- tests/interfaces/collections/messages/collections-write.spec.ts
- tests/interfaces/permissions/messages/permissions-request.spec.ts
- tests/store/message-store.spec.ts
As per "sender" requirement in https://github.com/TBD54566975/dwn-sdk-js/issues/91
> updated CollectionsQuery to return private messages authored by requester

- README.md
- package-lock.json
- package.json
- src/validation/json-schemas/jwk-verification-method.json
- tests/validation/json-schemas/jwk-verification-method.spec.ts
1. fixed regression on incompatibility with verification methods in ION DID Documents
2. added test to prevent future regression
> fixed regression on incompatibility with verification methods in ION DID Documents

- README.md
- src/interfaces/collections/messages/collections-query.ts
- src/interfaces/collections/messages/collections-write.ts
- src/interfaces/collections/types.ts
- src/interfaces/hooks/messages/hooks-write.ts
- src/interfaces/hooks/types.ts
- src/interfaces/permissions/messages/permissions-grant.ts
- src/interfaces/permissions/messages/permissions-request.ts
- src/interfaces/permissions/types.ts
- src/interfaces/protocols/messages/protocols-configure.ts
- src/interfaces/protocols/messages/protocols-query.ts
- src/interfaces/protocols/types.ts
- src/utils/time.ts
- src/validation/json-schemas/collections/collections-query.json
- src/validation/json-schemas/collections/collections-write.json
- src/validation/json-schemas/hooks/hooks-write.json
- src/validation/json-schemas/permissions/permissions-grant.json
- src/validation/json-schemas/permissions/permissions-request.json
- src/validation/json-schemas/protocols/protocols-configure.json
- src/validation/json-schemas/protocols/protocols-query.json
- tests/interfaces/collections/handlers/collections-write.spec.ts
- tests/interfaces/collections/messages/collections-write.spec.ts
- tests/utils/test-data-generator.ts
- tests/validation/json-schemas/collections/collections-query.spec.ts
- tests/validation/json-schemas/collections/collections-write.spec.ts
- tests/validation/json-schemas/protocols/protocols-configure.spec.ts
Fixes https://github.com/TBD54566975/dwn-sdk-js/issues/113
- Changes `dateCreated` to string
- Converted ISO format to appropriate precision as required 
- Edited the test cases
> Changes to date format

- package-lock.json
Uncaught exception in engine.io  - https://github.com/advisories/GHSA-r7qp-cfhv-p84w
handy as I am trying to mess with the build...
> fix for Severity: high

- README.md
- src/interfaces/collections/messages/collections-write.ts
- src/interfaces/collections/types.ts
- tests/interfaces/collections/handlers/collections-write.spec.ts
- tests/interfaces/collections/messages/collections-write.spec.ts
- tests/utils/test-data-generator.ts
with a couple of temporary assumptions that are pending decision regarding concept of lineage parent
> changed input to createLineageChild() to take unsigned CollectionsWrite message

- README.md
- build/compile-validators.js
- json-schemas/records/records-delete.json
- src/core/message.ts
- src/core/types.ts
- src/index.ts
- src/interfaces/permissions/messages/permissions-grant.ts
- src/interfaces/permissions/types.ts
- src/interfaces/records/handlers/records-delete.ts
- src/interfaces/records/handlers/records-write.ts
- src/interfaces/records/messages/records-delete.ts
- src/interfaces/records/messages/records-query.ts
- src/interfaces/records/messages/records-write.ts
- src/interfaces/records/records-interface.ts
- src/interfaces/records/types.ts
- tests/interfaces/protocols/handlers/protocols-configure.spec.ts
- tests/interfaces/records/handlers/records-delete.spec.ts
- tests/interfaces/records/handlers/records-query.spec.ts
- tests/interfaces/records/messages/records-delete.spec.ts
- tests/interfaces/records/messages/records-query.spec.ts
- tests/interfaces/records/messages/records-write.spec.ts
- tests/utils/test-data-generator.ts
#84 is still required to fully complete the feature
> #207 - implemented RecordsDelete

- src/utils/time.ts
change format of `dateCreated` and `dateUpdated` to UTC ISO-8601  timestamp
> UTC ISO-8601  timestamps

- package.json
Seems to be a Windows compat issue
> Remove ticks from echoed JSON

- README.md
- package-lock.json
- package.json
- src/index.ts
- src/interfaces/records/handlers/records-write.ts
- src/interfaces/records/messages/records-write.ts
- src/utils/cid.ts
- tests/utils/cid.spec.ts
* exported some CID utility functions
* fixed a bug caught by TypeScript compiler
* brought code coverage for `cid.ts` to 100%
> exported some CID utility methods

- README.md
- src/core/dwn-constant.ts
- src/core/message-reply.ts
- src/core/message.ts
- src/core/types.ts
- src/index.ts
- src/interfaces/protocols/handlers/protocols-query.ts
- src/interfaces/records/handlers/records-query.ts
- src/store/blockstore-level.ts
- src/store/index-level.ts
- src/store/storage-controller.ts
- tests/interfaces/records/handlers/records-delete.spec.ts
- tests/interfaces/records/handlers/records-query.spec.ts
- tests/interfaces/records/handlers/records-write.spec.ts
- tests/interfaces/records/messages/records-write.spec.ts
* added size check when returning encodedData
* opportunistically added some documentation
> #198 - added size check when returning encodedData

- .gitignore
- src/core/types.ts
- src/store/message-store-level.ts
- tests/dwn.spec.ts
- tests/interfaces/protocols/handlers/protocols-configure.spec.ts
- tests/interfaces/protocols/handlers/protocols-query.spec.ts
- tests/interfaces/records/handlers/records-delete.spec.ts
- tests/interfaces/records/handlers/records-query.spec.ts
- tests/interfaces/records/handlers/records-read.spec.ts
- tests/interfaces/records/handlers/records-write.spec.ts
- tests/store/data-store.spec.ts
- tests/store/message-store.spec.ts
so that it is consistent with the blockstore name "DATASTORE" for data store
> renamed blockstore name in message store to MESSAGESTORE for consistency

- src/core/protocol-authorization.ts
- tests/interfaces/records/handlers/records-write.spec.ts
I jumped the gun merging #277 and committed some lint errors
> Fix lint errors

- README.md
- build/license-check.cjs
- json-schemas/general-jws.json
- json-schemas/records/records-write.json
- package-lock.json
- package.json
- src/interfaces/records/types.ts
- src/utils/encryption.ts
- src/utils/jws.ts
- tests/utils/encryption.spec.ts
Added utility + schema + types for ECIES-SECP256K1 encryption according to the [TP18](https://github.com/TBD54566975/technical-proposals/pull/6) spec.
> #276 - added utility + schema + types for ECIES-SECP256K1 encryption

- README.md
- src/did/did-key-resolver.ts
- src/interfaces/records/messages/records-write.ts
- src/schema-validator.ts
- src/store/level-wrapper.ts
- src/store/storage-controller.ts
- tests/did/did-ion-resolver.spec.ts
- tests/did/did-key-resolver.spec.ts
- tests/interfaces/protocols/handlers/protocols-configure.spec.ts
- tests/interfaces/records/handlers/records-delete.spec.ts
- tests/interfaces/records/handlers/records-query.spec.ts
- tests/interfaces/records/handlers/records-read.spec.ts
- tests/interfaces/records/handlers/records-write.spec.ts
- tests/store/data-store.spec.ts
- tests/store/message-store.spec.ts
- tests/utils/test-data-generator.ts
- tsconfig.cjs.json
- tsconfig.json
Thanks to @diehuxx for merging my last PR, here's the next step to completing #278 .
There are still some places to fix up, the status looks like this right now:
```
Found 44 errors in 10 files.
Errors  Files
1  ../../../../../users/duncan/source/tbd/dwn-sdk-js/node_modules/ipfs-unixfs-importer/dist/src/index.d.ts:8
2  src/interfaces/records/messages/records-write.ts:434
1  src/schema-validator.ts:11
1  src/store/data-store-level.ts:6
2  src/store/index-level.ts:132
3  src/store/level-wrapper.ts:190
1  src/store/storage-controller.ts:102
3  tests/interfaces/permissions/messages/permissions-request.spec.ts:48
1  tests/interfaces/protocols/handlers/protocols-configure.spec.ts:131
29  tests/interfaces/records/handlers/records-query.spec.ts:297
```
> Turn on strict mode and fix tests

- package.json
> fix cjs `package.json`

- README.md
- json-schemas/records/records-write.json
- src/interfaces/records/messages/records-write.ts
- src/interfaces/records/types.ts
- tests/interfaces/records/handlers/records-query.spec.ts
- tests/interfaces/records/handlers/records-read.spec.ts
- tests/interfaces/records/handlers/records-write.spec.ts
- tests/interfaces/records/messages/records-write.spec.ts
- tests/utils/test-data-generator.ts
- tests/vectors/protocol-definitions/message.json
Part of the work for #310. There will be a follow up PR that does actual validation of the `protocolPath`, but priming this with the hope to get this breaking change early since there are PRs that will be modifying/adding protocol related logic.
> #310 - introduced protocolPath to update all affected tests

- README.md
- json-schemas/records/records-write.json
- src/core/dwn-error.ts
- src/utils/hd-key.ts
- src/utils/records.ts
- tests/interfaces/records/handlers/records-query.spec.ts
- tests/interfaces/records/handlers/records-read.spec.ts
- tests/interfaces/records/messages/records-write.spec.ts
- tests/utils/test-data-generator.ts
- tests/utils/url.spec.ts
1. implemented  key derivation scheme for encryption
2. boosted `url.ts` code coverage back to 100%
> #330 - implemented  key derivation scheme for encryption

- src/interfaces/permissions/messages/permissions-grant.ts
- src/interfaces/records/handlers/records-delete.ts
- tests/event-log/event-log-level.spec.ts
- tests/store/message-store.spec.ts
> Replace computeCid with Message.getCid

- README.md
- package-lock.json
- src/interfaces/records/handlers/records-delete.ts
- src/interfaces/records/handlers/records-write.ts
- src/jose/algorithms/signing/signers.ts
- src/store/message-store-level.ts
- src/store/message-store.ts
- src/store/storage-controller.ts
- src/utils/data-stream.ts
- src/utils/encoder.ts
- src/utils/object.ts
- tests/utils/object.spec.ts
> Use Record type where applicable

- src/index.ts
vandelay industries, import export
> Export Message class

- CONTRIBUTING.md
- Q_AND_A.md
- README.md
* added a Q&A document
* opportunistically updated `CONTRIBUTING.md`
> Added a Q&A document

- README.md
> Direct people to web5-js

- src/utils/url.ts
- tests/utils/url.spec.ts
> Allow protocol and schema URIs to omit slashes preceding path

- src/index.ts
> export `BaseMessage` and `MessageStoreOptions`

- CONTRIBUTING.md
- README.md
- package-lock.json
- package.json
- src/index.mts
- src/index.ts
- tests/dwn.spec.ts
- tests/handlers/events-get.spec.ts
- tests/handlers/messages-get.spec.ts
- tests/handlers/permissions-grant.spec.ts
- tests/handlers/permissions-request.spec.ts
- tests/handlers/protocols-configure.spec.ts
- tests/handlers/protocols-query.spec.ts
- tests/handlers/records-delete.spec.ts
- tests/handlers/records-query.spec.ts
- tests/handlers/records-read.spec.ts
- tests/handlers/records-write.spec.ts
- tests/store-dependent-tests.spec.ts
- tests/store/message-store-level.spec.ts
- tests/store/message-store.spec.ts
- tests/test-store-initializer.ts
- tests/test-stores.ts
- tests/test-suite.ts
- tsconfig.cjs.json
- tsconfig.json
Quite heavy-handed on both approach and implementation to get this support going after failing various experimentations....... so open to more elegant alternatives and/or improvements!
> Exported test suite so that store-dependent tests can be run from external repositories

- src/core/dwn-error.ts
- src/handlers/protocols-query.ts
- src/interfaces/protocols-configure.ts
- src/interfaces/protocols-query.ts
- tests/handlers/protocols-query.spec.ts
- tests/utils/test-data-generator.ts
Related to [TP26](https://github.com/TBD54566975/technical-proposals/pull/10)
This PR basically copies from #432 into `ProtocolsQuery`
> Grant authorize ProtocolsQuery

- CONTRIBUTING.md
- README.md
- package.json
Published an unstable build for testing `0.0.38-unstable-2023-07-13-test-suite-experiment`
> Exported the test suite in a much cleaner way than 1st attempt

- package-lock.json
- package.json
> version bump to 0.1.0

- README.md
- package-lock.json
- package.json
- src/utils/secp256k1.ts
- tests/utils/secp256k1.spec.ts
This is the last PR for the re-worked DWN encryption.
Definitely could still use some work to make things more bearable such as more utility methods, documentation, code refactoring etc, will get to those when I am back!
> #449 - Replaced existing key derivation function using a hardened scheme

- .vscode/launch.json
- src/types/records-types.ts
- tests/handlers/records-query.spec.ts
We already return it for RecordsRead.
> Return attestation with query results

- README.md
- src/core/protocol-authorization.ts
- src/interfaces/records-read.ts
- src/interfaces/records-write.ts
- src/types/protocols-types.ts
- src/types/records-types.ts
- tests/handlers/records-read.spec.ts
- tests/handlers/records-write.spec.ts
- tests/vectors/protocol-definitions/contribution-reward.json
- tests/vectors/protocol-definitions/friend-chat.json
- tests/vectors/protocol-definitions/group-chat.json
- tests/vectors/protocol-definitions/public-chat.json
- tests/vectors/protocol-definitions/stackoverflow.json
This PR implements the `any` and `context` rules of #463.
> Support additional protocol action rule groups

- src/index.ts
> export ProcolTypes

- .codesandbox/tasks.json
- README.md
I added a button for folks to open this project in Code Sandbox.
> adding config and button for codesandbox

- .codesandbox/tasks.json
Based on Frank's feedback, I'm adding in a bit more detail for the code sandbox configuration.
@frankhinek @diehuxx Let me know what you think!
> Adding more details to the codesandbox configuration

- README.md
- tests/handlers/protocols-configure.spec.ts
- tests/handlers/protocols-query.spec.ts
- tests/handlers/records-read.spec.ts
- tests/handlers/records-write.spec.ts
> remove use of dataStream for ProtocolsConfigure in tests

- README.md
I solved the issue #526 !
Do not hesitate to tell me if I have to modify something else. :blush:
> #526 - Fix typos in the README.md file

- README.md
- build/compile-validators.js
- json-schemas/signature-payloads/generic-signature-payload.json
- json-schemas/signature-payloads/records-write-author-signature-payload.json
- src/core/auth.ts
- src/core/dwn-error.ts
- src/core/message.ts
- src/interfaces/events-get.ts
- src/interfaces/messages-get.ts
- src/interfaces/permissions-grant.ts
- src/interfaces/permissions-request.ts
- src/interfaces/permissions-revoke.ts
- src/interfaces/protocols-configure.ts
- src/interfaces/protocols-query.ts
- src/interfaces/records-delete.ts
- src/interfaces/records-query.ts
- src/interfaces/records-read.ts
- src/interfaces/records-write.ts
- src/jose/jws/general/verifier.ts
- tests/handlers/permissions-grant.spec.ts
- tests/handlers/protocols-configure.spec.ts
- tests/handlers/protocols-query.spec.ts
- tests/handlers/records-query.spec.ts
- tests/handlers/records-write.spec.ts
* Added `ownerSignature` authentication
* Corrected naming in various places
> #439 - Added `ownerSignature` authentication & corrected naming

- src/handlers/protocols-query.ts
- src/types/protocols-types.ts
Fixing types in order to fix this line in web5-js
https://github.com/TBD54566975/web5-js/pull/241/files#diff-1b6d61b3a397e851119663ca61e15b3b7516a33bbe112f67441f6e7bc84774c3R162-R165
> Update ProtocolsQueryReply type to reflect actual object returned

- src/store/level-wrapper.ts
> #483 Fix level wrapper close implementation

- src/store/index-level.ts
Quick follow up from my previous PR.
> More item ID renames

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
Add accessibility features for markdown based on: https://github.blog/2023-10-26-5-tips-for-making-your-github-profile-page-accessible/
All other markdown files in the main folder have been checked too - they are okay :wink:
> Accessibility features for Markdown files

- src/index.ts
- src/utils/time.ts
- tests/utils/test-data-generator.ts
- tests/utils/time.spec.ts
Addresses #570 
- Adds and exports a helper function to create timestamps to use in dwn messages.
> adding helper function to create a timestamp

- benchmarks/store/message/message-store-level.js
- tests/utils/test-data-generator.ts
Created a simple benchmark to help measure the performance of MessageStoreLevel.
> MessageStoreLevel Benchmarking

- tests/handlers/records-write.spec.ts
Was experiencing testing intermittent test failures triggering a `409` `conflict` error.
> Add sleep between initial write and update to prevent intermittent test failures.

- src/types/protocols-types.ts
Updated docs for `ProtocolActionRules.can` to include `update` and `delete`
> Added update and delete to description of protocol actions

- package-lock.json
reference: https://security.snyk.io/package/npm/follow-redirects/1.15.2
> fix vuln for follow-redirects@1.15.2

- src/index.ts
This PR will export the following:
- `RecordsReadMessage`
- `RecordsSubscribeReply `
- `EventsQuery`
- `EventsQueryOptions`
> Exports needed for `@web5/agent` refactor

- package-lock.json
- package.json
- upgrade `@web5/dids` to `v0.4.1`
- bump `dwn-sdk-js` to `v0.2.18`
> upgrade `@web5/dids` to `v0.4.1` and bump `dwn-sdk-js` to `v0.2.18`

- .github/workflows/npm-publish-unstable.yml
Allow publishing unstable from any branch.
> Add Workflow Dispatch

- package-lock.json
- package.json
- bump `@web5/dids` dep to `0.4.3`
- bump package to `0.2.21`
> bump `@web5/dids` to `0.4.3` and package to `0.2.21`

- package-lock.json
- package.json
Upgrade foundational `@web5/dids` to `1.0.0`
> Upgrade foundational `@web5/dids` to `1.0.0`

- json-schemas/interface-methods/protocol-rule-set.json
- src/core/protocol-authorization.ts
- tests/features/records-tags.spec.ts
1. Separated non-patterned properties from pattern properties.
1. Avoided modifying rule set.
> Updates to tag enforcement PR

- package-lock.json
- package.json
- src/index.ts
export `RecordSubscriptionHandler` and bump release version.
> export RecordSubscriptionHandler

- package-lock.json
- package.json
upgrading `@web5/dids` from `v1.0.2` to `v1.0.3`
releasing `v0.3.4` of `dwn-sdk-js`
> update `@web5/dids` to fix regression

- tests/scenarios/subscriptions.spec.ts
Add scenario testing for `EventsSubscribe` filtered by `protocol` which includes permission messages (request, grant, revocation)
> EventsSubscribe filtered by `protocol`

- package-lock.json
- package.json
- migrating `Events` interface to `Messages` interface
- MessagesGet to MessagesRead
- Messages permission grants
- Filtering Messages by protocol
> Release v0.4.0

- package-lock.json
- package.json
- tests/features/resumable-tasks.spec.ts
For test run using external store implementation (ie. SQL)
> Added poller to a resumable task store test to increase reliability

- package-lock.json
- package.json
- src/index.ts
Export the test utility to be used in the tests in `dwn-server`.
Let me know if you'd rather have me duplicating the code or taking another approach.
> Exported Poller

- CONTRIBUTING.md
- README.md
This PR updates the Contributing Guide & README with mentions of Hacktoberfest 2024.
> Hacktoberfest 2024 MD Docs Update

- src/utils/secp256k1.ts
This PR adds the feature of setting the `lowS` flag to be `false` by default for the verification of secp256k1 signatures. 
Resolves #714
> Setting `lowS: false` by default for verification of secp256k1 signatures

- CONTRIBUTING.md
This PR fixes typos for the Code of Conduct in the Getting Started section of the CONTRIBUTING.md
Resolves #824
> Fixes typos for Code of Conduct in CONTRIBUTING.md

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
This pull request addresses various typographical errors in the Contribution Guide of the repository. The changes enhance the clarity and professionalism of the document, ensuring a better experience for contributors.
Changes Made:
- Corrected minor spelling and grammatical errors throughout the document.
- Improved readability and flow of certain sentences for better understanding.
Impact: These fixes do not alter any functionality but improve the overall presentation and readability of the Contribution Guide.
Related Issues: #824
> update: Fixed all the typo errors
