TBD54566975/dwn-sdk-js

.c8rc, .github/workflows/integrity-check.yml, .vscode/launch.json, CONTRIBUTING.md, README.md, package-lock.json, package.json, src/core/request.ts, src/dwn.ts, src/validation/json-schemas/index.ts, tsconfig.json
Made changes required to enable this SDK to be imported to spin up a nodejs DWN. Outlining journey that was taken in this PR:
1. Downstream TS nodejs project is not able to import this SDK:
Fixed incorrect `types` value in `package.json`, missing `esm` in path; but:
1. Crash on start because JSON-schema file import need import assertion:
Fixed by adding import assertions; but:
1. Build failure upon adding import assertions:
Fixed by update `module` value in `tsconfig` to enable import assertion syntax in TS. but:
1. ts-mocha throws TypeError: Unknown file extension ".ts" error when attempting to run tests using `npm run test:ndoe`:
After trying many things with no success, decided to use this opportunity to ditch `ts-mocha` and `ts-node` entirely by using building the tests and run tests …
=> Made changed required by downstream nodejs projects

README.md, src/did/did-key-resolver.ts, src/interfaces/collections/handlers/collections-write.ts, src/interfaces/collections/messages/collections-write.ts, src/jose/algorithms/signing/ed25519.ts, src/jose/algorithms/signing/secp256k1.ts, src/store/message-store-level.ts, src/utils/data.ts
This change was to implement a refactor of the codebase which would modify the files to use the encoder.ts file instead of directly referencing underlying dependencies/libraries.
=> refactored entire codebase to use encoder.ts

README.md, create-browser-bundle.cjs, create-bundle.cjs, esbuild-browser-config.cjs, karma.conf.cjs, package.json
This PR addresses issues using the sdk in the browser by including the necessary polyfills as a part of the bundle that's imported via `import { Dwn } from '@tbd54566975/dwn-sdk-js` in browser environments. Additionally, the browser tests and bundling script now use the same build configuration.
=> Browser Bundle

src/validation/json-schemas/collections/collections-write.json, tests/interfaces/collections/handlers/collections-query.spec.ts, tests/utils/test-data-generator.ts, tests/validation/json-schemas/collections/collections-write.spec.ts
Fixes #135 
- `"published": true` requires field `datePublished` be present
- `"published": false` requires field `datePublished` NOT be present
- Missing key `"published"` requires `datePublished` NOT be present
=> Better schema validation 135

build/esbuild-browser-config.cjs, package-lock.json, package.json
adjust bundle to use standard way of accessing the global `this` value (and hence the global object itself) across browser environments. `globalThis` is guaranteed to work in window and non-window contexts (e.g. web workers). This allows for consistent access to the global object without having to know which environment the code is being run in.
=> Browser extension compatibility

package-lock.json, package.json, src/utils/time.ts
This PR updates `getCurrentDateInHighPrecision` to use the upcoming [Temporal API](https://github.com/tc39/proposal-temporal). The Temporal API proposal is in Stage 3 and is not expected to change significantly. I think it is a better alternative to using the Performance API, which is intended for different purposes.
For now it is implemented using the recommended [polyfill](https://github.com/js-temporal/temporal-polyfill).
=> update getCurrentDateInHighPrecision to use Temporal API

.eslintrc.cjs, README.md, json-schemas/collections/collections-query.json, json-schemas/collections/collections-write.json, json-schemas/permissions/definitions.json, package-lock.json, package.json, src/core/auth.ts, src/interfaces/collections/handlers/collections-write.ts, src/interfaces/collections/messages/collections-query.ts, src/interfaces/collections/messages/collections-write.ts, src/interfaces/collections/types.ts, src/store/message-store-level.ts, src/utils/data.ts, tests/interfaces/collections/handlers/collections-write.spec.ts, tests/interfaces/collections/messages/collections-write.spec.ts, tests/utils/test-data-generator.ts, tests/validation/json-schemas/collections/collections-write.spec.ts
1. moved `recordId` to be a sibling property with `descriptor`
2. added `curly`  linter rule
3. renamed `validateSchema()`
=> moved `recordId` to be a sibling property with `descriptor`

README.md, src/interfaces/collections/handlers/collections-query.ts, src/interfaces/collections/handlers/collections-write.ts, src/interfaces/permissions/handlers/permissions-request.ts, src/interfaces/protocols/handlers/protocols-configure.ts, src/store/message-store-level.ts, src/store/message-store.ts, tests/interfaces/collections/handlers/collections-query.spec.ts, tests/store/message-store.spec.ts
If `published` is not set then behave as expected, but still, horrible security bug.
=> #170 - fixed bug where records with `published` explicitly set to `false` is included as published records

README.md, src/core/message.ts, src/index.ts, src/interfaces/collections/handlers/collections-query.ts, src/interfaces/collections/messages/collections-query.ts, src/interfaces/collections/messages/collections-write.ts, src/interfaces/collections/types.ts, src/utils/cid.ts, src/utils/string.ts, tests/interfaces/collections/handlers/collections-query.spec.ts, tests/interfaces/protocols/handlers/protocols-configure.spec.ts, tests/utils/test-data-generator.ts
`dateSort` has not yet been implemented for `CollectionsQuery` message types. Today, if a `CollectionQuery` contains the `dateSort` field the request will throw an error. We want to implement this behavior. ref: #167 
The solution to this problem entails the following:
1. Add a new `enum DateSortName` to encapsulate the raw string values that can be passed in.
2. Implement a `handleDateSort` function that accepts a `collectionQuery` and an array of `BaseMessage`.
The `handleDateSort` function extracts the `dateSort` value, and casts the BaseMessage type to a `CollectionWriteMessage` to gain access to the properties required to sort / filter entries. Then, we switch on `dateSort` and sort accordingly.
We can now support a `CollectionQuery` that contains a `dateSort` field.
=> Implement DateSort #167

README.md, package-lock.json, package.json, src/did/did-ion-resolver.ts, tests/did/did-ion-resolver.spec.ts
* Updated resolution endpoint to `beta.discover.did.microsoft.com`. `discover.did.microsoft.com` wasn't working
* Fixed an issue that was causing ION DID resolution to bork in browser extensions.
* `cross-fetch` is a [ponyfill](https://github.com/sindresorhus/ponyfill) that uses `XMLHTTPRequest` under the hood in browser environments. Unfortunately, `XMLHTTPRequest` cannot be used in MV3 browser extension background service workers. browser extensions get even more strict with `fetch` in that it cannot be referenced indirectly. 
Screenshot is a console in the context of a background service worker. Running `XMLHTTPRequestTest` shows that use of `XMLHTTPRequest` is not allowed. `IndirectReferenceTest` shows inability to use fetch when referenced indirectly
=> Fix did ion resolver

.github/workflows/npm-publish-unstable.yml, .github/workflows/npm-publish.yml, build/publish-unstable.sh, package.json
this is the first pass at release automation for npm - using the off the shelf github action recommendation.
To use this - you "simply" create a release on the github side - it takes care of the rest.
=> npm release automation from a github release

package.json
newer version of node use the `exports` property in `package.json` instead of `main` to figure out which file to import/require. Currently, the `package.json` in this repo only exports an `esm` distribution. This causes using the `cjs` distribution in newer versions of node to bork. 
This PR changes `exports` to support `cjs` and `esm`. Also added the `module` property because some bundlers look for it
=> Support all common variants of importing/requiring

README.md, src/store/blockstore-level.ts, src/store/message-store-level.ts, src/store/message-store.ts, src/utils/abort.ts, tests/store/message-store.spec.ts
currently it only contains a `signal: AbortSignal` that can be used to stop the activity of the called method
it's worth noting that this will only go so far, as `search-index`/`level`/etc. do not support anything like this, so ultimately it will only prevent future operations from happening
for example, given the following
```js
abortOr(signal, other())
```
even if the `signal` is already aborted, `other()` has already been called and therefore will not be stopped (unless `other` is changed to accept the `signal` as an argument)
=> #244 - add a `Options` to each method of `MessageStore`

README.md, package-lock.json, package.json, src/index.ts, src/store/blockstore-level.ts, src/store/create-level.ts, src/store/data-store-level.ts, src/store/message-store-level.ts, tests/dwn.spec.ts, tests/interfaces/protocols/handlers/protocols-configure.spec.ts, tests/interfaces/protocols/handlers/protocols-query.spec.ts, tests/interfaces/records/handlers/records-delete.spec.ts, tests/interfaces/records/handlers/records-query.spec.ts, tests/interfaces/records/handlers/records-read.spec.ts, tests/interfaces/records/handlers/records-write.spec.ts, tests/store/message-store.spec.ts
this will also be passed down when creating a `Dwn`, `MessageStoreLevel`, and `DataStoreLevel`
=> #244 - add a `createLevelDatabase` to allow customizing the `Level` used by `BlockstoreLevel`

README.md, src/store/blockstore-level.ts, src/store/create-level.ts, src/store/data-store-level.ts, src/store/message-store-level.ts, tests/store/message-store.spec.ts
i.e. if a developer provides their own `createLevelDatabase` then we will use that instead of `'level'`
in order to support this for both node and browser, we need to switch to using dynamic `import` (instead of `require`, as that's not defined for node when `"type": "module"`)
most of this commit is changing sync logic to `async` for that purpose (though it also allows for more flexibility when providing a custom `createLevelDatabase`)
=> #249- only import `'level'` when it's actually used

README.md, src/core/types.ts, src/interfaces/records/handlers/records-query.ts, src/interfaces/records/messages/records-query.ts, src/interfaces/records/types.ts, src/store/index-level.ts, src/store/message-store-level.ts, src/store/message-store.ts, src/store/storage-controller.ts, tests/store/message-store.spec.ts
this makes the API simpler to understand as `ExactCriterion` and `RangeCriterion` are expressed in the types rather than two separate parameters
it also entirely removes any chance of clashing if the same property is provided in both `exactCriteria` and `rangeCriteria`
=> #244 - use the same parameter types for `MessageStoreLevel.prototype.query` and `IndexLevel.prototype.query`

src/interfaces/records/messages/records-query.ts, tests/interfaces/records/handlers/records-query.spec.ts
this better matches many other APIs that operate with a [inclusive, exclusive) system (e.g. `String.prototype.slice`)
=> #250 and #257 - change `to` of query JSON schema to represent `lt` instead of `lte`

README.md, src/interfaces/protocols/handlers/protocols-configure.ts, src/interfaces/records/handlers/records-delete.ts, src/interfaces/records/handlers/records-read.ts, src/interfaces/records/handlers/records-write.ts, src/interfaces/records/records-interface.ts, src/store/blockstore-level.ts, src/store/data-store-level.ts, src/store/data-store.ts, src/store/level-wrapper.ts, src/store/message-store-level.ts, src/store/storage-controller.ts, src/utils/array.ts, tests/interfaces/records/handlers/records-delete.spec.ts, tests/interfaces/records/handlers/records-write.spec.ts, tests/store/index-level.spec.ts, tests/utils/test-data-generator.ts
this is done by reworking how data is stored inside `DataStoreLevel`
it has the following structure (`+` represents a sublevel and `->` represents a key->value pair):
```
'data' + <dataCid> -> <data>
'host' + <dataCid> + <tenant> + <messageCid> -> PLACEHOLDER_VALUE
```
this allows for the `<data>` to be shared for everything that uses the same `<dataCid>` while also making sure that the `<data>` can only be deleted if there are no `<messageCid>` for any `<tenant>` still using it
note we are currently doing this using `sublevel`, but that has the restriction of only allowing keys to contain characters after `34` and before `127`, meaning that if `<dataCid>`/`<tenant>`/`<messageCid>` ever allow for characters outside that range we will need to adjust
also switch from `logicalId`/`recordId` …
=> #84 - implement a reference counting system for data management to avoid duplication

README.md, src/interfaces/records/handlers/records-read.ts, src/store/data-store-level.ts, src/store/data-store.ts, src/store/storage-controller.ts, tests/interfaces/records/handlers/records-delete.spec.ts, tests/store/data-store.spec.ts
`ipfs-unixfs-importer` will split the `DataStream` into blocks, storing each in the `Blockstore` under a separate `CID`
unfortunately, we can only get the `CID` of the root block, so instead just leverage `level` to create a separate `partition` for the given `dataCid` and use that to delete everything in one go
ideally we'd have a way to get the `CID` of every block so that we can have the same `tenant`+`messageCid` association logic with each block instead of just the root (though this could result in a much larger metadata storage cost, but could also allow for deduplication of individual blocks)
=> #84 - deleting a `dataCid` should delete all blocks, not just the root

README.md, src/store/level-wrapper.ts, tests/store/data-store.spec.ts
`leveldb` seems to not immediately delete things from disk when calling `clear` (or `del`)
instead, `leveldb` will periodically remove nonreferenced data when it determines that it needs to (or if it's at an opportune moment, e.g. `open`)
this can be manually tested (we can't do an automated test because `approximateSize` isn't available on all platforms) by doing the following:
1. change any of the `DataStore` tests involving large amounts of data (e.g. `10_000_000`) to be `it.only`
2. repeatedly do `npm run test:node`
3. observe the size of `TEST-DATASTORE` on disk
the size of `TEST-DATASTORE` should not go above ~3× the size of the data (e.g. `30_000_000`)
furthermore, if you then changed that test to not do anything other than `open`, you should see the size of `TEST-DATASTORE` …
=> #84 - clearing all blocks for a `dataCid` should remove the data from disk right now

README.md, json-schemas/records/records-write.json, src/core/dwn-error.ts, src/index.ts, src/interfaces/protocols/handlers/protocols-query.ts, src/interfaces/records/handlers/records-query.ts, src/interfaces/records/messages/records-write.ts, src/interfaces/records/types.ts, src/store/storage-controller.ts, src/utils/encryption.ts, src/utils/hd-key.ts, src/utils/records.ts, src/utils/secp256k1.ts, tests/interfaces/records/handlers/records-query.spec.ts, tests/interfaces/records/handlers/records-read.spec.ts, tests/interfaces/records/handlers/records-write.spec.ts, tests/utils/records.spec.ts, tests/utils/secp256k1.spec.ts, tests/utils/test-data-generator.ts, tests/vectors/protocol-definitions/email.json
There is A LOT of quality-of-life stuff that can be done to make the SDK much easier to use as follow ups, but this is nevertheless the first complete milestone that lights up the encryption feature.
Some features to be added in follow up PR(s) include:
1. Add `protocolPath` to every protocol-based `RecordsWrite`
1. Extend `protocol-context` derivation scheme further
1. Add more key derivation schemes
=> #276 - added encryption support to RecordsWrite

README.md, json-schemas/protocol-rule-set.json, src/core/protocol-authorization.ts, src/interfaces/records/handlers/records-read.ts, src/interfaces/records/messages/records-read.ts, tests/interfaces/records/handlers/records-read.spec.ts, tests/interfaces/records/handlers/records-write.spec.ts, tests/vectors/protocol-definitions/email.json, tests/vectors/protocol-definitions/social-media.json
Addresses part of #285
* `json-schemas/protocol-rule-set.json`: Previously `ProtocolRule`s allowed exactly one of (`anyone`, `author`, `recipient`). This PR allows for AT LEAST one of those; i.e. we may have multiple of (`anyone`, `author`, `recipient`).
=> Support protocol authorized reads

README.md, src/core/dwn-error.ts, src/index.ts, src/interfaces/protocols/messages/protocols-configure.ts, src/interfaces/protocols/messages/protocols-query.ts, src/interfaces/protocols/types.ts, src/interfaces/records/messages/records-query.ts, src/interfaces/records/messages/records-write.ts, src/utils/url.ts, tests/interfaces/protocols/handlers/protocols-configure.spec.ts, tests/interfaces/protocols/handlers/protocols-query.spec.ts, tests/interfaces/protocols/messages/protocols-configure.spec.ts, tests/interfaces/protocols/messages/protocols-query.spec.ts, tests/interfaces/records/handlers/records-query.spec.ts, tests/interfaces/records/handlers/records-read.spec.ts, tests/interfaces/records/handlers/records-write.spec.ts, tests/interfaces/records/messages/records-query.spec.ts, tests/interfaces/records/messages/records-write.spec.ts, tests/utils/url.spec.ts
Addresses part of https://github.com/TBD54566975/dwn-sdk-js/issues/265
Revises a previous attempt #314 
To ensure that protocols URIs are bucketed intuitively,
1. `#create` methods auto-normalize protocols for an ergonomic developer experience
2. non-normalized protocols are rejected from DWNs
Going to add a little more test coverage in the morning to bring relevant files back up to 100%
=> Reject messages with nonnormalize protocol URIs

README.md, json-schemas/protocol-definition.json, src/core/dwn-error.ts, src/core/protocol-authorization.ts, src/interfaces/protocols/types.ts, tests/interfaces/records/handlers/records-write.spec.ts
Fully addresses #306
* Add `dataFormats` to protocol definition JSON schema
* Validate that incoming RecordsWrites are within the allowed `dataFormats`
=> #306 Validate data format on protocol authd writes

README.md, src/index.ts, src/interfaces/records/messages/records-write.ts, src/utils/hd-key.ts, src/utils/records.ts, tests/interfaces/records/handlers/records-query.spec.ts, tests/interfaces/records/handlers/records-read.spec.ts, tests/interfaces/records/handlers/records-write.spec.ts, tests/interfaces/records/messages/records-write.spec.ts, tests/utils/records.spec.ts
Added a number of useful quality-of-life improvements for devs using the SDK for encryption:
1. When using root private key, derivation path of `[]` is no longer required to be specified
2. Encryption input used to create an encrypted message now only accepts the root public key
=> Quality-of-life improvements for devs using the SDK for encryption

README.md, src/core/dwn-error.ts, src/interfaces/protocols/messages/protocols-configure.ts, src/interfaces/protocols/messages/protocols-query.ts, src/interfaces/records/messages/records-query.ts, src/interfaces/records/messages/records-write.ts, src/utils/url.ts, tests/interfaces/protocols/handlers/protocols-configure.spec.ts, tests/interfaces/protocols/messages/protocols-configure.spec.ts, tests/interfaces/records/handlers/records-query.spec.ts, tests/interfaces/records/handlers/records-write.spec.ts, tests/interfaces/records/messages/records-query.spec.ts, tests/interfaces/records/messages/records-write.spec.ts, tests/store/message-store.spec.ts, tests/utils/url.spec.ts, tests/vectors/protocol-definitions/dex.json
Finishes addressing https://github.com/TBD54566975/dwn-sdk-js/issues/265
Copying lots of code from https://github.com/TBD54566975/dwn-sdk-js/pull/317
To ensure that schema URIs are bucketed intuitively,
1. `#create` methods auto-normalize schema for an ergonomic developer experience
2. non-normalized schemas are rejected from DWNs
=> Reject messages with nonnormalized schema URIs

json-schemas/protocol-rule-set.json, src/core/protocol-authorization.ts, src/interfaces/protocols/types.ts, tests/interfaces/records/handlers/records-write.spec.ts, tests/validation/json-schemas/protocols/protocols-configure.spec.ts, tests/vectors/protocol-definitions/credential-issuance.json, tests/vectors/protocol-definitions/dex.json, tests/vectors/protocol-definitions/email.json, tests/vectors/protocol-definitions/message.json, tests/vectors/protocol-definitions/social-media.json
Addresses one aspect of #326
A shortcoming of the existing protocol allow rule structure is that we can only specify one rule per actor. For example, this means cannot create both a rule allowing `author` of `image` to `write` and a rule `author` of `image/reply` to `read`. By refactoring `allow` to be an array, protocol allow rules become more flexible.
=> Refactor protocol allow rules

README.md, json-schemas/protocol-definition.json, src/core/dwn-error.ts, src/core/protocol-authorization.ts, src/interfaces/protocols/messages/protocols-configure.ts, src/interfaces/protocols/types.ts, src/utils/protocols.ts, tests/interfaces/protocols/handlers/protocols-configure.spec.ts, tests/interfaces/protocols/messages/protocols-configure.spec.ts, tests/interfaces/records/handlers/records-query.spec.ts, tests/interfaces/records/handlers/records-read.spec.ts, tests/interfaces/records/handlers/records-write.spec.ts, tests/utils/test-data-generator.ts, tests/validation/json-schemas/protocols/protocols-configure.spec.ts, tests/vectors/protocol-definitions/credential-issuance.json, tests/vectors/protocol-definitions/dex.json, tests/vectors/protocol-definitions/email.json, tests/vectors/protocol-definitions/message.json, tests/vectors/protocol-definitions/social-media.json
Another step in the refactor outlined in #326. Also, fully addresses feature #333.
#326
* Change property `label` to `recordDefinitions`. Make `recordDefinitions` an array, where each element has `id`, `schema`, and `dataFormats`
#333
* Makes `schema` optional in protocol auth'd `RecordsWrites`. (`schema` was previously required for protocol `RecordsWrites`.)
Other
* Remove duplicate tests and flesh out tests for `ProtocolAuthrorization.getRuleSet`, particularly testing for new error code `DwnErrorCode.ProtocolAuthorizationMissingRuleSet`.
=> #333 #326 Refactor protocol recordTypes

README.md, json-schemas/protocol-rule-set.json, src/core/protocol-authorization.ts, src/interfaces/protocols/types.ts, tests/interfaces/records/handlers/records-write.spec.ts, tests/validation/json-schemas/protocols/protocols-configure.spec.ts, tests/vectors/protocol-definitions/credential-issuance.json, tests/vectors/protocol-definitions/dex.json, tests/vectors/protocol-definitions/email.json, tests/vectors/protocol-definitions/message.json, tests/vectors/protocol-definitions/social-media.json
We decided to move back to this semantic naming pattern (e.g. `of`, `can`). And we noticed that flattening the `can` field (previously `actions`) from an array into a single string makes future changes to the protocol DSL simpler.
=> Rename and flatten protocol action rules

src/index.ts
Now that `dwn-server` has been converted to TS (and `web5-js` this week), we'd like to be able to import the `RecordsReadReply` type from `dwn-sdk-js`
For example:
https://github.com/TBD54566975/dwn-server/blob/02c6a01fe783f4e605d7fd0b8b7fdcc8aac9ab97/src/json-rpc-handlers/dwn/process-message.ts#L32-L38
=> Add RecordsReadReply to exports

README.md, json-schemas/protocol-definition.json, src/core/protocol-authorization.ts, src/interfaces/protocols/types.ts, tests/interfaces/records/handlers/records-write.spec.ts, tests/utils/test-data-generator.ts, tests/validation/json-schemas/protocols/protocols-configure.spec.ts, tests/vectors/protocol-definitions/credential-issuance.json, tests/vectors/protocol-definitions/dex.json, tests/vectors/protocol-definitions/email.json, tests/vectors/protocol-definitions/message.json, tests/vectors/protocol-definitions/minimal.json, tests/vectors/protocol-definitions/private-protocol.json, tests/vectors/protocol-definitions/social-media.json
Keeping this one short. In the next PR, I'll remove `records` from the `ProtocolRuleSets` so we don't have to repeat it all over the place.
=> Protocol rename records -> structure

README.md, json-schemas/protocol-rule-set.json, src/core/protocol-authorization.ts, tests/interfaces/records/handlers/records-write.spec.ts, tests/validation/json-schemas/protocols/protocols-configure.spec.ts
#345
Tweaking JSON schema and making tests hopefully a little more robust in order to enforce presence of `of` when `who` === `author` or `recipient`.
=> #345 - Require `of` in protocol action rules

json-schemas/protocol-rule-set.json, src/core/protocol-authorization.ts, src/interfaces/protocols/types.ts, tests/interfaces/records/handlers/records-write.spec.ts, tests/vectors/protocol-definitions/credential-issuance.json, tests/vectors/protocol-definitions/dex.json, tests/vectors/protocol-definitions/email.json, tests/vectors/protocol-definitions/social-media.json
Last change we have planned for the protocol definition DSL. Remove `records` from `ProtocolRuleSets`.
There are some tradeoffs about different ways to structure `type ProtocolRuleSet` so it is ergonomic for consumers of `dwn-sdk-js`. The requirements are:
1. The `$actions` field must be optional and will have type `ProtocolActionRule` when it is present.
2. Any other string property will have type `ProtocolRuleSet`.
In my opinion, this is the least gross option. All other options entail writing unsightly typescript.
Benefit: Doesn't require lots of `(...as ProtocolActionRule)` or `(...as ProtocolRuleSet), and doesn't involve weird `Symbol` conversion logic.
Drawback: Least strict typing. Not very different from vanilla JS experience.
```typescript
export type ProtocolRuleSet = { …
```
=> Remove records keyword from protocol definitions

README.md, json-schemas/records/records-write.json, src/interfaces/records/messages/records-query.ts, src/interfaces/records/messages/records-write.ts, src/interfaces/records/types.ts, tests/interfaces/records/handlers/records-query.spec.ts, tests/interfaces/records/handlers/records-read.spec.ts, tests/interfaces/records/handlers/records-write.spec.ts, tests/interfaces/records/messages/records-write.spec.ts, tests/utils/test-data-generator.ts, tests/validation/json-schemas/records/records-write.spec.ts
* allowed `recipient` only if `protocol` exists in a RecordsWrite
* made `recipient` an optional parameter
* opportunistic rename `recipientDid` to `recipient` for consistency
=> #284 - allowed `recipient` only if `protocol` exists in a RecordsWrite

Q_AND_A.md, README.md, src/store/index-level.ts, src/store/level-wrapper.ts, src/store/message-store-level.ts, src/utils/abort.ts, src/utils/object.ts
Refactored the Level implementation of data indexing in preparation for inevitable Protocol participant requirements:
1.  Refactored `put()` by simplifying how indexes are stored for deletion purposes
1. Refactored `query()` (thanks @diehuxx !!)
1. Refactored `findExactMatches()` and `findRangeMatches()` by removing `findMatches()`
1. Refactored `delete()`
1. Removed `Match`
1. Added a lot of comments/documentation
1. A lot of renames
=> index-level refactoring

src/core/protocol-authorization.ts, tests/interfaces/records/handlers/records-write.spec.ts
No change in functionality or test coverage. I just think this is slightly cleaner.
=> Move ProtocolAuthorization#verifyTypes

README.md, src/core/message-reply.ts, src/dwn.ts, src/index.ts, src/interfaces/protocols/handlers/protocols-query.ts, src/interfaces/records/handlers/records-query.ts, src/store/index-level.ts, src/types/records-types.ts, tests/dwn.spec.ts, tests/event-log/event-log-level.spec.ts, tests/interfaces/events/handlers/events-get.spec.ts, tests/interfaces/events/messages/events-get.spec.ts, tests/interfaces/messages/handlers/messages-get.spec.ts, tests/interfaces/permissions/messages/permissions-request.spec.ts, tests/interfaces/records/handlers/records-query.spec.ts, tsconfig.cjs.json, tsconfig.json
In a future PR, we should remove `MessageReply` as a class and/or consolidate it with `BaseMessageReply`, return type of `processMessage()` is messy at the moment, and we will have a clear path forward tomorrow.
=> #298 - enabled noImplicitAny rule and fixed all errors triggered

README.md, json-schemas/records/records-write.json, src/interfaces/records-read.ts, tests/handlers/records-read.spec.ts
This is already allowed in `RecordsQuery`. A recipient may query their received, unpublished messages
=> Allow recipients to always read their received messages

README.md, json-schemas/permissions/definitions.json, json-schemas/permissions/permissions-grant.json, json-schemas/permissions/permissions-request.json, package-lock.json, src/core/message-reply.ts, src/dwn.ts, src/handlers/events-get.ts, src/handlers/messages-get.ts, src/handlers/permissions-request.ts, src/handlers/protocols-configure.ts, src/handlers/protocols-query.ts, src/handlers/records-delete.ts, src/handlers/records-query.ts, src/handlers/records-read.ts, src/handlers/records-write.ts, src/interfaces/permissions-grant.ts, src/interfaces/permissions-request.ts, src/types/permissions-types.ts, tests/core/message-reply.spec.ts, tests/handlers/permissions-request.spec.ts, tests/interfaces/permissions-request.spec.ts, tests/utils/test-data-generator.ts
First PR implementing [Technical Proposal 26](https://github.com/TBD54566975/technical-proposals/pull/10)
* Update JSON schema for `PermissionsRequest` and `PermissionsGrant`
* Add handler and tests for `PermissionsRequest`
* Cut out outdated message structure from `PermissionsGrant`. This PR doesn't test creation or handling of `PermissionsGrant` messages. That'll come in the next one.
* Reduce `scope` and `conditions` in JSON schema to bare bones. I'll add scope and conditions options back in as I implement the functionality of each one.
=> Create and handle PermissionsRequest

README.md, json-schemas/permissions/permissions-grant.json, src/core/dwn-error.ts, src/dwn.ts, src/handlers/permissions-grant.ts, src/interfaces/permissions-grant.ts, src/types/permissions-types.ts, tests/handlers/permissions-grant.spec.ts, tests/handlers/permissions-request.spec.ts, tests/interfaces/permissions-grant.spec.ts, tests/interfaces/permissions-request.spec.ts, tests/utils/test-data-generator.ts
This PR creates and processes `PermissionsGrant` messages. It does NOT implement grant-based authorization of other DWN messages. That'll be added in the next PR.
=> Create and process PermissionsGrant messages

package.json
In React Native, the directive priority order goes:
`react-native > browser > main`
`react-native` previously did not set values for `./dist/esm/src/index.js` or `./dist/cjs/src/index.js`, so it would instead use the values from the `browser` directive. This caused react native to consume `./dist/bundles/browser.js`, which causes issues in that environment, which requires workarounds in the react native apps that consume it.
To fix, this PR directly sets values for `./dist/esm/src/index.js` and `./dist/cjs/src/index.js` to always point to the esm version.
=> Use esm for react-native directive

README.md, package-lock.json, package.json
1. Removed `npm-run-all` dependency
2. Overridden vulnerable transitive `make-dir` dependency of `c8`
=> Updated vulnerable dependencies flagged by npm audit

README.md, src/utils/secp256k1.ts, tests/validation/json-schemas/jwk-verification-method.spec.ts
The recent polyfill in #396 broke react-native. I removed the polyfill and moved to the README. Polyfills and globals should probably be left to user's projects and moved to READMEs. After merging, downstream projects will need to update their READMEs to reflect this change.
Misc: formatted README with Prettier
=> remove node polyfill and move to readme

package-lock.json, package.json
`npm audit` is flagging an issue with `word-wrap`.
```
word-wrap  *
Severity: moderate
word-wrap vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-j8xg-fqg3-53r7
No fix available
node_modules/word-wrap
optionator  >=0.8.3
Depends on vulnerable versions of word-wrap
node_modules/optionator
eslint  2.5.0 - 2.5.2 || >=6.7.0
Depends on vulnerable versions of optionator
node_modules/eslint
eslint-plugin-todo-plz  *
Depends on vulnerable versions of eslint
node_modules/eslint-plugin-todo-plz
```
Vuln here: https://security.snyk.io/vuln/SNYK-JS-WORDWRAP-3149973
Community fix here: https://github.com/jonschlinkert/word-wrap/pull/33#issuecomment-1511820080
=> Update vulnerable version of word-wrap

README.md, package-lock.json, package.json, src/core/auth.ts, src/core/message-reply.ts, src/core/message.ts, src/dwn.ts, src/handlers/messages-get.ts, src/handlers/permissions-grant.ts, src/handlers/permissions-request.ts, src/handlers/protocols-configure.ts, src/handlers/records-delete.ts, src/handlers/records-write.ts, src/index.ts, src/interfaces/records-read.ts, src/interfaces/records-write.ts, src/store/message-store-level.ts, src/store/storage-controller.ts, src/types/event-types.ts, src/types/hooks-types.ts, src/types/message-store.ts, src/types/message-types.ts, src/types/messages-types.ts, src/types/method-handler.ts, src/types/permissions-types.ts, src/types/protocols-types.ts, src/types/records-types.ts, src/types/snapshots-types.ts, tests/core/message-reply.spec.ts
1. Removed Record specific properties from `BaseMessage`
1. Renamed `BaseMessage` to `GenericMessage` - Makes more sense from the perspective of the store implementor, as they don't care about inheritance/extension
1. Opportunistic rename of `Reply" types
=> Updated BaseMessage in preparation for external Store interface implementations

CONTRIBUTING.md, package-lock.json, package.json, src/types/data-store.ts, src/types/event-log.ts, src/types/message-store.ts, tests/dwn.spec.ts, tests/handlers/events-get.spec.ts, tests/handlers/messages-get.spec.ts, tests/handlers/permissions-grant.spec.ts, tests/handlers/permissions-request.spec.ts, tests/handlers/protocols-configure.spec.ts, tests/handlers/protocols-query.spec.ts, tests/handlers/records-delete.spec.ts, tests/handlers/records-query.spec.ts, tests/handlers/records-read.spec.ts, tests/handlers/records-write.spec.ts, tests/interfaces/records-write.spec.ts, tests/store/data-store-level.spec.ts, tests/store/message-store-level.spec.ts, tests/store/message-store.spec.ts, tests/test-store-initializer.ts
1. Made tests independent of specific store implementations
Still need more changes to make testing external implementation truly seamless, but at least the story is much better than before.
1. Moved store implementation specific tests into their own dedicated suites.
=> Refactored tests to be independent of store implementation

README.md, package-lock.json, package.json, src/utils/encryption.ts
This PR replaces the problematic and poorly maintained [eccrypto](https://github.com/bitchan/eccrypto) library with [eciesjs](https://github.com/ecies/js).
> **Note**
> Although not unexpected, it is worth emphasizing that this is a breaking change in the sense that any data previously encrypted with `Encryption.eciesSecp256k1Encrypt()` cannot be decrypted `Encryption.eciesSecp256k1Decrypt()` after this PR has been merged.  However, given the issues discovered recently with record encryption, this seems to be an acceptable at this time.
- `eccrypto` has not been updated since March 2021 whereas `eciesjs` is being actively maintained by a responsive maintainer.
- `eccrypto` depends on 5 packages ([acorn](https://www.npmjs.com/package/acorn), …
=> Replace eccrypto with eciesjs

package-lock.json, package.json
This PR is primarily to address a high severity vulnerability:
- [CVE-2023-36665](https://github.com/advisories/GHSA-h755-8qp9-cq85) - protobufjs Prototype Pollution vulnerability
The `package-lock.json` file was re-created to allow for the patched `v7.2.4` version of `protobufjs` to be installed.
Once this PR is merged [Dependabot alert #8](https://github.com/TBD54566975/dwn-sdk-js/security/dependabot/8) can be closed.
Additionally, in the process of resolving this security vulnerability, one other change was made:
1. Discovered that listing `make-dir` as a runtime dependency is not necessary to resolve [CVE-2022-25883](https://github.com/advisories/GHSA-c2qf-rxjj-qqgw) as long as the override for `v4.0.0` exists in `package.json` (which it already did).
=> Fix for CVE-2023-36665

README.md, json-schemas/interface-methods/records-write.json, src/interfaces/records-write.ts, src/types/data-store.ts, tests/interfaces/records-write.spec.ts, tests/validation/json-schemas/records/records-write.spec.ts
Discovered by Tyler Amirault in Slack:
https://discord.com/channels/937858703112155166/969272658501976117/1128421823223185579
=> #434 - fixed bug that allowed creation of protocol record with parentId but missing contextId

tests/handlers/records-write.spec.ts, tests/test-suite.ts
@amika-sq reported the need to run the exported test suites multiple times, however this is not currently supported because
1. Any number of times the custom store overrides will all take place immediately before test suite is run regardless how many time it is supposed to run, resulting in only the last override taking effect for all test suite runs.
2. A test is modifying a protocol definition used across test suite runs, causing 3 tests dependent on the protocol definition to always fail  in subsequent test suite runs.
=> Added support for multi-implementation test suite runs in one external repository

README.md, json-schemas/interface-methods/protocol-definition.json, json-schemas/interface-methods/protocols-query.json, src/handlers/protocols-configure.ts, src/handlers/protocols-query.ts, src/handlers/records-query.ts, src/interfaces/protocols-configure.ts, src/interfaces/protocols-query.ts, src/store/message-store-level.ts, src/types/message-store.ts, src/types/protocols-types.ts, tests/handlers/protocols-query.spec.ts, tests/handlers/records-read.spec.ts, tests/utils/test-data-generator.ts, tests/validation/json-schemas/protocols/protocols-configure.spec.ts, tests/vectors/protocol-definitions/credential-issuance.json, tests/vectors/protocol-definitions/dex.json, tests/vectors/protocol-definitions/email.json, tests/vectors/protocol-definitions/message.json, tests/vectors/protocol-definitions/minimal.json, tests/vectors/protocol-definitions/private-protocol.json, tests/vectors/protocol-definitions/social-media.json
1. Added concept of published ProtocolsConfigures
1. Added support for unauthenticated queries for published ProtocolsConfigures
1. Retain `authorization` property when returning results for `ProtocolsQuery`
1. Refactored `RecordsQuery` handler for cleaner auth logic (should be helpful for adding permission auth)
=> Added support for unauthenticated queries for published ProtocolsConfigures

json-schemas/interface-methods/records-query.json
ProtocolPath should be a filter property:
https://github.com/TBD54566975/dwn-sdk-js/blob/fe7e4912bf105a1f9b912584cf4bcd05a751d8d5/src/types/records-types.ts#L103
But fails due to schema validation: 
```sh
Error: /descriptor/filter: must NOT have additional properties
at validateJsonSchema (file:///Users/akmb2/workspace/github.com/zion/simple-web5-chat/node_modules/@tbd54566975/dwn-sdk-js/dist/esm/src/schema-validator.js:25:11)
at Message.validateJsonSchema (file:///Users/akmb2/workspace/github.com/zion/simple-web5-chat/node_modules/@tbd54566975/dwn-sdk-js/dist/esm/src/core/message.js:58:9)
at RecordsQuery.<anonymous> (file:///Users/akmb2/workspace/github.com/zion/simple-web5-chat/node_modules/@tbd54566975/dwn-sdk-js/dist/esm/src/interfaces/records-query.js:55:21)
at Generator.next …
```
=> add protocolPath to json schema validation  in records query filter

src/store/index-level.ts, tests/store/index-level.spec.ts
When querying IndexLevel using the `EqualFilter` with a number, there was an bug where values that didn't match that filter were getting returned. 
This bug was due to the way that LevelDB iterators work. 
Previously, the code to find exact matches was using a LevelDB iterator to seek to the first value that had the prefix of: `<propertyName>\x00<propertyValue>`. It would then use that iterator to take all values until it no longer started with that prefix.
This was problematic, as when the caller is querying via a number, not all digits that start with a given digit are equal to one another. For example, `digit\x0010` has the same prefix as `digit\x00100`, even though one has the value of `10`, while the other has a value of `100`. 
To fix, we need to add the delimiter used to separate …
=> Fix number equality filter bug in IndexLevel

package-lock.json, package.json, src/interfaces/records-write.ts, tsconfig.json
This PR removes use of es6 `#` private fields (which were introduced in a recent commit) to regain cjs compatibility. we're retaining cjs due to electron's lack of esm support.
=> cjs compatibility

README.md, src/utils/time.ts, tests/core/message.spec.ts, tests/handlers/permissions-revoke.spec.ts, tests/handlers/protocols-configure.spec.ts, tests/handlers/protocols-query.spec.ts, tests/handlers/records-delete.spec.ts, tests/utils/test-data-generator.ts
Experienced this issue and tracked it down:
https://github.com/TBD54566975/dwn-sdk-js/issues/481
This might be some sort of precision bug within Temporal itself, I'm not really sure how various NodeJS systems handle time precision.
But in these cases there simply needs to be a gap in time for the testing logic, increasing the gap by an additional millisecond will make sure these tests are accurate.
=> Sleep for 2ms to avoid time-sensitive test failures

README.md, build/create-browser-bundle.cjs, build/create-cjs-bundle.cjs, package.json, src/index-stores.ts, src/index.ts, tests/test-stores.ts
React Native currently cannot import `MessageStoreLevel`, `DataStoreLevel`, or `EventLogLevel`, as they are in a named export called `./stores`. 
React Native currently does not support named exports (but it is coming in a future update), so we have to manually import those classes from the `dist/esm/src/index-stores` directory. Example: https://github.com/TBD54566975/web5-wallet/pull/52#discussion_r1291668116
This is not ideal, but really causes issues when other packages use the `./stores` import. For example, in @frankhinek's agent refactor PR, we're using the `/stores` named export here: https://github.com/TBD54566975/web5-js/pull/168/files#r1298468034. React Native is not able to do this, causing the `@web5/agent` package to also be incompatible with React Native.
We have a couple of …
=> Move level store exports to index.ts

README.md, json-schemas/interface-methods/protocol-rule-set.json, tests/handlers/records-read.spec.ts, tests/handlers/records-write.spec.ts
We are working on another way to address these use cases with a new protocol concept called `roles`. In the meantime, it's best we disable the `any` and `context`. I'll rip out / update the code implementing of these protocol rules in a later PR. This PR is minimal for expediency.
=> Temporarily disable protocol any and context rules

README.md, src/store/level-wrapper.ts
Addresses #483.
Currently, when we open our `LevelWrapper` db, we `sleep(200)` repeatedly until it is open. Per the [abstract-level documentation](https://github.com/Level/abstract-level#events), the `db` emits events for `open`, `opening`, `closed`, and `closing`. So we simply need to wrap the event emitter in a promise and await that promise..
=> Remove sleep() from db.open()

src/core/message.ts, src/handlers/records-delete.ts, src/store/storage-controller.ts, src/types/message-types.ts
Previous `TimestampedMessage` referred to messages with `dateModified` in the descriptor. We removed `dateModified` and now all messages use `messageTimestamp`. So we can use type `GenericMessage` instead of `TimestampedMessage`.
=> Remove extraneous TimestampedMessage type

src/core/dwn-constant.ts, src/index.ts
Exporting Filter, Sort and Pagination types for consumption by external MessageStores.
Lower max maxDataSizeAllowedToBeEncoded. We are currently checking this against the dataSize, which is the binary data size. However when we store it we are base64 encoding the data, which has an approximate increase of 33%, this was causing some issues going right above the limit in SQL.
Upon some rough calculations of the 65k limit for most SQL - 33% reduction, I rounded down to the nice number of 42_000.
=> Export Sort and Pagination types.

src/event-log/event-log-level.ts
`EventLogLevelConfig` is used when constructing an `EventLogLevel` instance. 
Currently, the `location` property in the config is required. This means that the default location used in the `EventLogLevel` constructor of `'EVENTLOG'` is never actually used.
Other stores, like `MessageStoreLevel` and `DataStoreLevel` have their config locations optional, and then will use the non-null assertion operator to use default values if there wasn't a location defined ([MessageStoreLevel code here](https://github.com/TBD54566975/dwn-sdk-js/blob/main/src/store/message-store-level.ts#L38-L55) and [DataStoreLevel code here](https://github.com/TBD54566975/dwn-sdk-js/blob/main/src/store/data-store-level.ts#L29-L40)).
This PR makes the `EventLogLevelConfig.location` property optional to match the other …
=> Make EventLogLevelConfig.location optional

src/did/did-ion-resolver.ts, tests/did/did-ion-resolver.spec.ts
Refactored to include the fetch method within the DidIonResolver class.
Now sinon can stub out fetch when the network is unavailable.
=> offline did resolution in tests were not working

README.md, src/handlers/records-query.ts, src/handlers/records-read.ts, src/types/records-types.ts, tests/handlers/records-query.spec.ts, tests/handlers/records-read.spec.ts
This is necessary to allow a third party retainer of the message to ensure the authenticity of the message author.
=> #439 - Return `authorization` in queries and reads

json-schemas/authorization-owner.json, json-schemas/authorization.json, src/core/auth.ts, src/core/message.ts, src/core/protocol-authorization.ts, src/interfaces/events-get.ts, src/interfaces/messages-get.ts, src/interfaces/permissions-grant.ts, src/interfaces/permissions-request.ts, src/interfaces/permissions-revoke.ts, src/interfaces/protocols-configure.ts, src/interfaces/protocols-query.ts, src/interfaces/records-delete.ts, src/interfaces/records-query.ts, src/interfaces/records-read.ts, src/interfaces/records-write.ts, src/interfaces/snapshots-create.ts, src/types/message-types.ts, tests/handlers/protocols-configure.spec.ts, tests/handlers/protocols-query.spec.ts, tests/handlers/records-write.spec.ts, tests/interfaces/records-write.spec.ts, tests/utils/test-data-generator.ts, tests/validation/json-schemas/records/records-query.spec.ts
A pure rename to improve readability (for most cases).
=> #439 - Appended 'Signature' to` author` and `owner` under `authorization`

README.md, src/interfaces/permissions-grant.ts, tests/interfaces/permissions-grant.spec.ts
Fixes #530 
1. Normalize `schema` and `protocol`  properties of `PermissionScope` object in `create` method of `PermissionGrant` interface.
2. Added tests to validate normalization.
=> Normalize schema and protocol in create method of permission-grant

src/did/did-ion-resolver.ts, tests/did/did-ion-resolver.spec.ts
Removed `networkAvailable` tests in `DidIonResolver` as it wasn't working in all environments. 
Created issue to track: https://github.com/TBD54566975/dwn-sdk-js/issues/544
=> revert network unavailable stub, breaks in the browser test

README.md, package.json, src/dwn.ts, src/types/records-types.ts, tests/dwn.spec.ts, tests/handlers/records-delete.spec.ts, tests/handlers/records-query.spec.ts, tests/handlers/records-read.spec.ts, tests/handlers/records-write.spec.ts
This commit introduces a handleRecordsWrite function meant to be used in place of the existing processMessage which is eventually meant to be replaced as described in issue #289.
This commit also updates the relevant tests in records-(write|delete|read|query).ts files, which were using processMessage and replaces its usage with the new handleRecordsWrite.
It also introduces a few new tests in dwn.spec.ts, enough to bring uncovered lines of this function to 0 (more specifically, the new test is meant to cover the exception path).
=> Introduce Dwn.handleRecordsWrite function

README.md, src/store/index-level.ts, src/store/message-store-level.ts, tests/event-log/event-log-level.spec.ts, tests/store/index-level.spec.ts, tests/store/message-store.spec.ts
The `MessageStores`'s `IndexLevel` doesn't take into account partitioning for the tenant.
This causes the following issue:
if `alice` + `bob` both put the same message in their respective tenant, the index updates accordingly and both can query.
But if `bob` deletes the message, `alice` can no longer query for the message, but she CAN do a get from the message store with the messageCid since that's still partitioned.
This PR adds a partition to the `IndexLevel` to index for each tenant separately. There are more storage-efficient ways of handing this, but puling in this low-overhead fix to handle the bug.
As a side note, we also allow "empty" querying, currently this is done by injecting the `tenant` into the index, as well as into the query. If an empty filter is provided, it will ALWAYS …
=> MessageStore Index tenant partitioning

src/interfaces/records-write.ts, src/types/records-types.ts, src/utils/records.ts, tests/handlers/records-delete.spec.ts, tests/handlers/records-read.spec.ts, tests/handlers/records-write.spec.ts, tests/interfaces/records-write.spec.ts, tests/utils/test-data-generator.ts
Noticed some lingering incorrect naming due to recent inclusion of author signature in query/read results. `UnsignedRecordsWriteMessage` turned out to be no longer referenced upon fixing the names.
=> Removed `UnsignedRecordsWriteMessage` type

src/index.ts, src/interfaces/records-read.ts, src/utils/data-stream.ts, src/utils/encoder.ts, tests/end-to-end-tests.spec.ts, tests/handlers/records-read.spec.ts, tests/handlers/records-write.spec.ts, tests/interfaces/records-read.spec.ts, tests/test-suite.ts, tests/utils/test-data-generator.ts, tests/vectors/protocol-definitions/thread-role.json
- Wrote a scenario test for a multi-party chat app that make use of:
- Role-based authorization for chat thread participants
- Protocol context derived key for chat thread encryption
- Participant protocol path derived key for context derived private key encryption
- Other minor improvements and fixes
=> Scenario test for a multi-party encrypted chat app

README.md, src/core/dwn-error.ts, src/core/protocol-authorization.ts, src/handlers/records-write.ts, src/interfaces/records-read.ts, src/interfaces/records-write.ts, tests/handlers/records-write.spec.ts
Currently, protocol record validation and authorization are coupled. This PR attempts to separate the two actions into distinct calls `ProtocolAuthorization.validate()` for RecordsWrites and `ProtocolAuthorization.authorize()` for any incoming message. There is some duplication of code across `validate` and `authorize`. The most significant of which is that we iterate up the ancestor chain with `constructAncestorMessageChain()`. If we think this is an unacceptable inefficiency, we can fix by updating `verifyProtocolPath` to look at only the parent instead of the entire ancestor chain.
=> Make protocol record validation and authorization distinct actions

README.md, build/compile-validators.js, json-schemas/interface-methods/number-range-filter.json, json-schemas/interface-methods/records-filter.json, src/types/records-types.ts, tests/handlers/records-query.spec.ts
This commit fixes #525.  It adds `dataSize` optional property in RecordsFilter.
It adds a new json schema definition number-range-filter with properties gt, lt, gte, and lte.
Also adds new tests to cover half-open, open, and closed range queries.
=> Add range filter support for dataSize

README.md, package-lock.json, package.json, src/utils/encryption.ts, src/utils/records.ts, src/utils/secp256k1.ts, tests/utils/encryption.spec.ts, tests/utils/secp256k1.spec.ts
Updated eciesjs library, that now supports compressed secp256k1 public key, and adjusted codes.
Converted key creation methods to produce compressed secp256k1 public key.
Resolves #397
=> Add support for compressed secp256k1 publicKey

.github/workflows/integrity-check.yml, README.md, codecov.yml
Added Codecov to the CI pipeline to display test coverage on pull requests and on Readme badge.
See #534.
=> Add codecov coverage job in `integrity-check.yml`

README.md, json-schemas/interface-methods/protocol-rule-set.json, src/core/protocol-authorization.ts, src/interfaces/records-write.ts, src/types/protocols-types.ts, tests/handlers/records-write.spec.ts, tests/utils/test-data-generator.ts, tests/vectors/protocol-definitions/anyone-collaborate.json, tests/vectors/protocol-definitions/author-update.json, tests/vectors/protocol-definitions/friend-role.json, tests/vectors/protocol-definitions/recipient-update.json, tests/vectors/protocol-definitions/thread-role.json
The `update` action allows an actor to update an existing record. This contrasts with the `write` action which allows only the creator of a record to update it. In other words:
1. `write` allows a DID to create a record and update the record they have created
2. `update` allows a DID to update a record, regardless of initial author
=> Add protocol update action

src/store/index-level.ts
Currently `cursor` can be the message CID, or be the ugly-looking string that represents an index key. This creates confusion when for newbies like me, especially there are literally variables named `cursor` in the SAME function that mean different things.
=> Disambiguating meaning of cursor

json-schemas/interface-methods/messages-get.json, json-schemas/interface-methods/permissions-request.json, json-schemas/interface-methods/permissions-revoke.json, json-schemas/interface-methods/protocols-query.json, json-schemas/interface-methods/records-delete.json, json-schemas/interface-methods/records-read.json, package-lock.json, src/core/dwn-error.ts, src/interfaces/events-get.ts, src/interfaces/messages-get.ts, src/interfaces/permissions-grant.ts, src/interfaces/permissions-request.ts, src/interfaces/permissions-revoke.ts, src/interfaces/protocols-configure.ts, src/interfaces/protocols-query.ts, src/interfaces/records-delete.ts, src/interfaces/records-query.ts, src/interfaces/records-read.ts, src/interfaces/records-write.ts, src/utils/time.ts, tests/utils/time.spec.ts
Addresses #324 
After digging into this, it appears a lot of progress has already been made on schema-based validation in #147 but adding some more robust validation by ensuring the timestamp is parseable. 
- updated `interface-method` schemas that have timestamps without the `date-time` schema reference
- added `validateTimestamp` to ensure timestamps are valid
=> adding time schema validation to other interface method schemas

json-schemas/interface-methods/protocol-rule-set.json, src/core/dwn-error.ts, src/core/protocol-authorization.ts, src/handlers/records-delete.ts, src/interfaces/records-delete.ts, src/types/protocols-types.ts, tests/handlers/records-delete.spec.ts, tests/handlers/records-write.spec.ts, tests/utils/test-data-generator.ts, tests/vectors/protocol-definitions/author-can.json, tests/vectors/protocol-definitions/free-for-all.json, tests/vectors/protocol-definitions/friend-role.json, tests/vectors/protocol-definitions/post-comment.json, tests/vectors/protocol-definitions/recipient-can.json, tests/vectors/protocol-definitions/thread-role.json
Addresses #557. Support protocol authorized deletes for both actors (`author`, `recipient`, `anyone`) and roles (`$globalRole`, `$contextRole`).
=> Support protocol authorized RecordsDelete

json-schemas/interface-methods/records-filter.json, src/handlers/records-query.ts, src/types/records-types.ts, src/utils/records.ts, tests/handlers/records-query.spec.ts, tests/interfaces/records-query.spec.ts
Added the following filters to RecordsQuery:
`published`
`dataCid`
`datePublished`
`dateUpdated` (messageTimestamp)
=> Add missing filters to RecordsQuery

json-schemas/authorization-owner.json, json-schemas/authorization.json, src/core/auth.ts, src/core/message.ts, src/core/protocol-authorization.ts, src/core/records-grant-authorization.ts, src/handlers/records-query.ts, src/interfaces/events-get.ts, src/interfaces/messages-get.ts, src/interfaces/permissions-grant.ts, src/interfaces/permissions-request.ts, src/interfaces/permissions-revoke.ts, src/interfaces/protocols-configure.ts, src/interfaces/protocols-query.ts, src/interfaces/records-delete.ts, src/interfaces/records-query.ts, src/interfaces/records-read.ts, src/interfaces/records-write.ts, src/types/message-types.ts, tests/handlers/protocols-configure.spec.ts, tests/handlers/protocols-query.spec.ts, tests/handlers/records-write.spec.ts, tests/interfaces/records-write.spec.ts, tests/utils/test-data-generator.ts
This was a deferred PR from previous PR to reduce noise.
I have opted for `signature` over `signerSignature` as the name for the canonical/default term as the message signature. Let me know if you have a better term, but `authorSignature` is definitely logically incorrect.
=> #564 - Renamed author signature for consistency

src/core/auth.ts, src/core/dwn-error.ts, src/jose/jws/general/verifier.ts, src/utils/jws.ts, tests/jose/jws/general.spec.ts, tests/jose/jws/verifier.spec.ts
1. Fixed bug where a new cache is created every time the DWN performs a signature check
1. Removed the need to instantiate a new instance of `GeneralJwsVerifier` every time DWN performs a signature check
1. Improved perf by not doing DID resolution when the signature check result is already cached
1. Minor error code naming improvements
=> Fixed bug on usage of `GeneralJwsVerifier` and improved its usability

package-lock.json, package.json, src/jose/algorithms/signing/ed25519.ts
We have some circular dependencies in `dwn-sdk-js` that we should consider removing/resolving. One circular dependency in particular is causing issues in consumers of `dwn-sdk-js`.
In [this PR](https://github.com/TBD54566975/dwn-sql-store/pull/9) `dwn-sql-store`, we are getting the following error upon running tests:
> ReferenceError: Cannot access 'ed25519' before initialization
at <anonymous> (/home/runner/work/dwn-sql-store/dwn-sql-store/node_modules/@tbd54566975/dwn-sdk-js/src/jose/algorithms/signing/signature-algorithms.ts:8:17)
at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
at async importModuleDynamicallyWrapper (node:internal/vm/module:431:15)
at async formattedImport …
=> Remove circular dependency causing problems in lib consumer

package.json
The RN bundle specified was CJS but RN is compatible with ESM (via babel)
=> tweak rn to depend on esm bundle

src/core/dwn-error.ts, src/core/protocol-authorization.ts, src/interfaces/protocols-configure.ts, tests/handlers/records-delete.spec.ts, tests/handlers/records-write.spec.ts, tests/interfaces/protocols-configure.spec.ts, tests/vectors/protocol-definitions/recipient-can.json
Allow actions rules of the format `who: 'recipient', can: ...` for `update` and `delete`.
We will not use direct recipient for `read`, `write`, or `query` because:
* Recipients are always allowed to `read`.
* `write` entails ability to create and update, whereas `update` only allows for updates. There is no 'recipient' until the record has been created, so it makes no sense to allow `recipient` to `write`.
* At this time, `query` is only authorized using `roles`, so allowing direct recipients to query is outside the scope of this PR.
=> Authorize direct recipient of protocol records

json-schemas/interface-methods/records-query.json, src/handlers/records-query.ts, src/store/message-store-level.ts, src/types/message-store.ts, src/types/message-types.ts, src/types/records-types.ts, tests/handlers/records-query.spec.ts, tests/store/message-store.spec.ts
When bubbling up this change into `web5-js` @frankhinek had a comment about a more intuitive developer experience.
https://github.com/TBD54566975/web5-js/pull/268#discussion_r1388020519
I know we originally wanted to be explicit with what the `cursor` value should be, but I think that it's more appropriate for the spec rather than the naming of the variable.
@thehenrytsai what are your thoughts here?
=> Replace `paginationMessageCid` with `cursor` for pagination query options and response.

json-schemas/interface-methods/records-delete.json, src/core/protocol-authorization.ts, src/interfaces/records-delete.ts, src/utils/records.ts, tests/scenarios/delegated-grant.spec.ts, tests/vectors/protocol-definitions/thread-role.json
1. Added delegated grant support for `RecordsDelete`
1. Merged mainline positive and negative cases of delegated grants into one test to reduce context switching.
=> #564 - Added delegated grant support for RecordsDelete

package-lock.json, package.json
This PR bumps the versions of the `readable-stream` and `@types/readable-stream` dependencies.
While troubleshooting an issue with `RecordsWrite` overwrites in `web5-js` I attempted to use a locally linked `dwn-sdk-js` package to add logging but encountered a series of errors that prevented building from completing successfully:
```
src/dwn-api.ts:434:43 - error TS2345: Argument of type '{ descriptor: Descriptor & RecordsWriteDescriptor; authorization: AuthorizationModel; recordId: string; contextId?: string; ... 4 more ...; target: string; }' is not assignable to parameter of type 'RecordOptions'.
Type '{ descriptor: Descriptor & RecordsWriteDescriptor; authorization: AuthorizationModel; recordId: string; contextId?: string; ... 4 more ...; target: string; }' is not assignable to type '{ …
```
=> Bump readable-stream version

json-schemas/interface-methods/records-filter.json, src/types/records-types.ts, tests/handlers/records-query.spec.ts
We already index the `author` property for `RecordsWrite` but we currently don't expose it as a filter.
=> Add `author` to `RecordsFilter`

src/core/message-reply.ts, src/index.ts
- When fixing circular deps `DateSort` was exported as a type, however it is an enum and to use the enum values you must export it without the type flag.
- Adding an optional `cursor` to `UnionMessageReply` so that `processMessage` for a generic message will respond with an appropriate type.
=> Update `DateSort` export and `UnionMessageReply`

src/core/grant-authorization.ts, src/core/records-grant-authorization.ts, src/handlers/records-read.ts, src/handlers/records-write.ts, src/interfaces/protocols-query.ts, src/interfaces/records-write.ts, src/utils/records.ts, tests/interfaces/records-write.spec.ts, tests/scenarios/delegated-grant.spec.ts
1. Added delegated grant scoping for `RecordsWrite`.
1. Refactored code so that delegated grant evaluation can reuse the permissions grant evaluation logic.
=> #564 - Added delegated grant scoping for `RecordsWrite`

src/core/dwn-error.ts, src/dwn.ts, src/handlers/records-write.ts, tests/dwn.spec.ts, tests/handlers/records-query.spec.ts, tests/handlers/records-write.spec.ts
There are some cases where a DWN might have an initial `RecordsWrite` message used to create a record, but not have the data associated with it.
Until now this was only possible through a special method on the DWN `synchronizePrunedInitialRecordsWrite` which was only used for sync. However, there are multi-participant scenarios where this same behavior is necessary.
This PR exposes that functionality to the general processing of `RecordsWrite` messages.
If a `RecordsWrite` message is supplied without any data, it is checked that it is the initial `RecordsWrite` and indexes it as not being the latest state, this prevents it from being queryable without any data until a subsequent `RecordsWrite` with data is available.
Addresses: https://github.com/TBD54566975/dwn-sdk-js/issues/628
=> Allow initial RecordsWrite without data to be written to the DWN.

src/handlers/messages-get.ts, src/handlers/records-query.ts, src/handlers/records-read.ts, src/handlers/records-write.ts, src/store/storage-controller.ts, src/types/message-types.ts, src/types/records-types.ts, tests/core/message.spec.ts, tests/handlers/records-query.spec.ts, tests/handlers/records-read.spec.ts, tests/handlers/records-write.spec.ts
All ears on better/more performant implementation but this is the simplest approach with fastest turnaround to unblock usage.
=> Included initial write to RecordsRead and RecordsQuery if they are not initial write

src/jose/algorithms/signing/ed25519.ts, src/utils/secp256k1.ts
This PR primarily focuses on performance improvement for the two digital signature algorithms supported by `dwn-sdk-js.
In [this Discord thread](https://discord.com/channels/937858703112155166/1181470744023146538) @shamilovtim noted significant delays while profiling [web5-wallet](https://github.com/TBD54566975/web5-wallet) performance.
During the troubleshooting process, a tangentially related issue was discovered that unnecessarily reduces the performance of `Ed25519` and `secp256k1` sign operations.  While updating `dwn-sdk-js` to the v2.0 versions of `@noble/ed5519` and `@noble/secp256k1` in PR #396, unnecessary conversions to hex format were added in the `sign()` method (but not `verify()`).
The result of this change is that `sign()` performance degrades rapidly as the data size of …
=> Remove unnecessary conversions to hex format

src/core/auth.ts, src/core/dwn-error.ts, src/core/grant-authorization.ts, src/core/message.ts, src/core/protocol-authorization.ts, src/core/records-grant-authorization.ts, src/handlers/events-get.ts, src/handlers/events-query.ts, src/handlers/messages-get.ts, src/handlers/protocols-configure.ts, src/handlers/records-read.ts, src/handlers/records-write.ts, src/interfaces/events-get.ts, src/interfaces/events-query.ts, src/interfaces/messages-get.ts, src/interfaces/permissions-grant.ts, src/interfaces/permissions-request.ts, src/interfaces/permissions-revoke.ts, src/interfaces/protocols-configure.ts, src/interfaces/protocols-query.ts, src/interfaces/records-delete.ts, src/interfaces/records-query.ts, src/interfaces/records-read.ts, src/interfaces/records-write.ts, src/types/permissions-types.ts, tests/handlers/protocols-configure.spec.ts
- Turned RecordsGrantAuthorization.authorizeQuery/Read/Write parameters into `input` instead for readability
- Renamed `authorize()` to `authorizeOwner()`
- Renamed `authorizeProtocolRecord()` to `verifyProtocolRecordScope()`
- Renamed `authorizeFlatRecord()` to `verifyFlatRecordScope()`
- Renamed `GrantAuthorization.authorizeGenericMessage()` to `GrantAuthorization.performBaseValidation()`
- Renamed `validateMessageSignatureIntegrity()` to `validateSignatureStructure()`
- Introduced `RecordsPermissionsGrantMessage` for readability
=> Refactored grant related code for readability

src/index.ts, tests/utils/test-data-generator.ts
I've found myself wanting to reach for this when trying to create benchmarking in an external repo, and potentially useful within web5-js (I think they duplicate much of this class though).
A community member is also looking to create some benchmarking tools and was asking for this to be exported.
=> Export `TestDataGenerator` class

src/core/message-reply.ts, src/dwn.ts, src/handlers/events-get.ts, src/handlers/events-query.ts, src/handlers/messages-get.ts, src/handlers/permissions-grant.ts, src/handlers/permissions-request.ts, src/handlers/permissions-revoke.ts, src/handlers/protocols-configure.ts, src/handlers/records-delete.ts, src/handlers/records-write.ts, src/index.ts, src/types/event-types.ts, src/types/message-types.ts, src/types/messages-types.ts, src/types/method-handler.ts, src/types/protocols-types.ts, src/types/records-types.ts, tests/core/message-reply.spec.ts, tests/dwn.spec.ts, tests/handlers/events-get.spec.ts, tests/handlers/events-query.spec.ts, tests/handlers/messages-get.spec.ts, tests/scenarios/events-query.spec.ts
`UnionMessageReply` was not fully in sync with the actual replies.
- `data` is actually within `record` for a `RecordsReadReply`.
- modified `events` to `entries` for `EventsGetReply` and `EventsQueryReply`
- modified `messages` to `entries` for `MessagesGetReply`
This way all of the individual replies can be represented by:
```typescript
/**
* Catch-all message reply type. It is recommended to use GenericMessageReply or a message-specific reply type wherever possible.
*/
export type UnionMessageReply = GenericMessageReply & {
/**
* Resulting message entries or events returned from the invocation of the corresponding message.
* e.g. the resulting messages from a RecordsQuery, or array of messageCid strings for EventsGet or EventsQuery
* Mutually exclusive with `record`.
*/
entries?: …
```
=> Align `UnionMessageReply` with the various replies that `processMessage` 

package-lock.json, package.json, src/did/did-key-resolver.ts, tests/utils/test-data-generator.ts
As part of taking over Finn's PoW work, I see that the `dwn-server` repo has a [`Profile`](https://github.com/TBD54566975/dwn-server/blob/main/tests/utils.ts#L31) wrapper that wraps key signer over `Persona`. The signer can (and arguably should) be included as a first-class/built-in utility for `Persona` to avoid this overhead, so I did.
Hiked the version to v0.2.10 in preparation of a new release to consume this in `dwn-server`.
=> v0.2.10 + Added private key signer as part of Persona creation

README.md, package-lock.json, package.json, src/core/tenant-gate.ts, src/dwn.ts, src/index.ts, tests/dwn.spec.ts
Upon adding support tenant registration and tenant gate in `dwn-server`, it occurred to me that `isTenant()` is not a perfect fit, because they can be a tenant, but have agreed to an old/expired terms-of-service, in which case they still should be denied access.
`isActiveTenant()` address the intent better.
All ears if you have an even better word than "active".
=> Renamed isTenant() to isActiveTenant() to better support intent

src/did/did-ion-resolver.ts, tests/did/did-ion-resolver.spec.ts
This is temporary until we replace our resolvers w/ the `@web5/dids` package.
=> use the TBD engineering endpoint for `did:ion`

src/core/dwn-error.ts, src/event-log/event-emitter-stream.ts, tests/event-log/event-emitter-stream.spec.ts
Set `maxListeners` option on `EventEmitter` to 0, which represents infinity.
This is a soft limit of when to issue warnings into the stderr of the system but does not have an effect on actual event listeners.
https://nodejs.org/api/events.html#eventsdefaultmaxlisteners
Exposed a way to capture errors, with the default being sent to `console.error` as before.
=> Enhance EventEmitterStream with options

build/compile-validators.js
Currently Ajv throws a warning for union types:
Adding the option `allowUnionTypes: true` removes the warning.
=> Allow Union Types in JSON Schema parsing

Q_AND_A.md, package-lock.json, package.json, src/core/dwn-error.ts, src/handlers/records-read.ts, src/handlers/records-write.ts, src/index.ts, src/store/data-store-level.ts, src/store/storage-controller.ts, src/types/data-store.ts, src/utils/data-stream.ts, tests/handlers/records-delete.spec.ts, tests/handlers/records-write.spec.ts, tests/store/data-store-level.spec.ts
1. Removed the need for SQL-like DB for reference counting.
2. Removed  the need for `associate()` implementation entirely.
3. Removed the need to return `dataCid` from data store and handled the `dataCid` computation within the `dwn-sdk-js` itself.
4. As a result, simplified the Level implementation which now only requires 135 lines of code.
5. Various other complexity that went away because of the simplification.
In summary an implementer now only needs to implement `put()`, `get()` and `delete()`.
=> Simplified Data Store interface

src/store/blockstore-mock.ts, src/utils/cid.ts, tests/store/blockstore-mock.spec.ts
Another production-readiness fix. This is particularly useful when dealing with large files and a necessity in a large-scale production service environment.
Prior to this PR, we used the In-Memory Blockstore to compute the CID, which would temporarily store the entire data in memory until the the CID is computed. (e.g. 10 people uploading 1GB at the same time would require 10GB of memory)
Did a sanity test with a 5 GB data stream: original implementation would consume gigabytes of memory during the computation of the CID; the new implementation consumes zero/little additional memory (minus the process itself).
=> Added a mock blockstore to compute CID of large data streams with no/tiny memory usage

.gitignore, package-lock.json, package.json, src/dwn.ts, tests/utils/test-data-generator.ts
This PR will:
- Bump the `@web5/dids` package from `0.3.0` to `0.4.0`.
- Adds a DID resolver cache to the default instantiate of a `Dwn`.  The cache is a TTL cache with a 15 minute default timeout.  It uses a persistent LevelDB cache which will keep approximately 8,000 DID documents in an in-memory cache before flushing to disk.  Since the cache entries are persisted to disk, they will survive process restarts.
- Bump `@tbd54566975/dwn-sdk-js` to `0.2.17` so it can be published to NPM Registry.
=> Bump `@web5/dids` and add DID Resolver cache

json-schemas/jwk-verification-method.json, tests/validation/json-schemas/jwk-verification-method.spec.ts
This PR will:
- Update the JWK verification method schema to support `JsonWebKey` in addition to `JsonWebKey2020`.
- All Web5 SDKs use `JsonWebKey` when creating DHT DIDs
- `JsonWebKey` used by the [DID DHT method specification](https://did-dht.com/#representing-keys)
- Eventually all Web5 SDKs will use `JsonWebKey` for DIDs per [this open issue](https://github.com/TBD54566975/web5-spec/issues/73).
> JsonWebKey2020 is deprecated, as it was published as a part of a now-defunct [CCG draft here](https://www.w3.org/community/reports/credentials/CG-FINAL-lds-jws2020-20220721/). It has been replaced with the recommendation-track JsonWebKey defined in [vc-jose-cose](https://w3c.github.io/vc-jose-cose/).
=> Update JWK Verification Method Schema to support `JsonWebKey`

Q_AND_A.md, json-schemas/interface-methods/protocol-rule-set.json, src/core/protocol-authorization.ts, src/interfaces/protocols-configure.ts, src/types/protocols-types.ts, tests/handlers/records-delete.spec.ts, tests/handlers/records-write.spec.ts, tests/vectors/protocol-definitions/anyone-collaborate.json, tests/vectors/protocol-definitions/author-can.json, tests/vectors/protocol-definitions/free-for-all.json, tests/vectors/protocol-definitions/friend-role.json, tests/vectors/protocol-definitions/post-comment.json, tests/vectors/protocol-definitions/recipient-can.json, tests/vectors/protocol-definitions/slack.json, tests/vectors/protocol-definitions/thread-role.json
Next up: reintroduce `delete` action and disambiguate it from `co-delete`.
=> Renamed protocol actions `update` -> `co-update` and `delete` -> `co-delete`

json-schemas/interface-methods/protocol-rule-set.json, src/core/protocol-authorization.ts, src/types/protocols-types.ts, tests/interfaces/protocols-configure.spec.ts, tests/scenarios/delegated-grant.spec.ts, tests/validation/json-schemas/protocols/protocols-configure.spec.ts, tests/vectors/protocol-definitions/author-can.json, tests/vectors/protocol-definitions/chat.json, tests/vectors/protocol-definitions/contribution-reward.json, tests/vectors/protocol-definitions/credential-issuance.json, tests/vectors/protocol-definitions/dex.json, tests/vectors/protocol-definitions/email.json, tests/vectors/protocol-definitions/free-for-all.json, tests/vectors/protocol-definitions/friend-role.json, tests/vectors/protocol-definitions/message.json, tests/vectors/protocol-definitions/post-comment.json, tests/vectors/protocol-definitions/slack.json, tests/vectors/protocol-definitions/social-media.json, tests/vectors/protocol-definitions/thread-role.json
This is considered an unnecessary and potentially confusing "sugar" now that we have explicit `create` and `update` actions.
=> Removed `write` protocol action

src/event-log/event-emitter-stream.ts, src/handlers/events-subscribe.ts, src/handlers/records-subscribe.ts, src/types/subscriptions.ts, tests/event-log/event-emitter-stream.spec.ts, tests/event-log/event-stream.spec.ts
Adding `tenant` parameter to the subscribe method in order to better organize the pub/sub.
=> add tenant to EventsStream interface subscribe method

json-schemas/permission-grant.json, src/core/protocol-authorization.ts, src/index.ts, src/interfaces/records-write.ts, src/protocols/permissions.ts, src/types/permissions-grant-descriptor.ts, src/types/protocols-types.ts, tests/features/author-delegated-grant.spec.ts, tests/features/owner-delegated-grant.spec.ts, tests/features/owner-signature.spec.ts, tests/features/permissions.spec.ts, tests/test-suite.ts
This will replace the entire `Permissions` interface.
This PR only contains the support of permission life-cycle management through Request, Grant, and Revocation records.
The actual replacing/swapping out the existing logic that depends on `Permissions` messages will come in the next PR.
=> Introduced first-class Permissions protocol

src/core/dwn-error.ts, src/index.ts, src/jose/algorithms/signing/signature-algorithms.ts, src/types/jose-types.ts, src/utils/secp256r1.ts, tests/jose/jws/general.spec.ts, tests/utils/secp256r1.spec.ts
Added support for signing and verifying keys with Secp256r1 curve. Oracle KMS utilizes these keys and we needed the verification piece for our implementation, so thought we would share with the TBD team how we went about it and extend to cover the signing piece as well.
Uses @noble/curves/p256 package in approach similar to utils/secp256k1.ts. I have included tests with 100% code coverage of the secp256r1.ts file and also tested locally with the generated key pairs for end-to-end signing and verifying in the context of our implementation. Open to any suggestions for improving the implementation/excited to hear your thoughts!
=> Signing and verifying with Secp256r1 keys

package-lock.json, package.json
- includes `tags` support for records
- includes `secp256r1` signing/verification support.
=> Bump to `v0.2.23`

package-lock.json
Addressing CVE-2023-36665 for `protobufjs` which is a transient dependency of `ipfs-unixfs`
https://github.com/TBD54566975/dwn-sdk-js/security/dependabot/12
=> update protobuf to address CVE-2023-36665

src/core/protocol-authorization.ts, tests/handlers/records-write.spec.ts
The error message that comes back with `DwnErrorCode.ProtocolAuthorizationParentlessIncorrectProtocolPath` contained a reference to the incorrect `parentId`. This PR updates the value to the correct `parentContextId` to help with debugging.
=> Update error message to include reference to the correct `parentContextId`

package-lock.json, package.json
For some reason `WebkitHeadless` was not connecting during the tests and therefore timing out.
Upgrading playwright to the latest version remedied the issue.
=> Upgrade Playwright

.vscode/launch.json, json-schemas/interface-methods/records-delete.json, src/handlers/records-delete.ts, src/interfaces/records-delete.ts, src/interfaces/records-write.ts, src/store/storage-controller.ts, src/types/records-types.ts, src/utils/records.ts, tests/features/records-prune.spec.ts, tests/interfaces/records-write.spec.ts, tests/test-suite.ts
1st of a few PRs for the `prune` feature. This one lights up the capability for anyone who is able to perform `RecordsDelete`, which should be immediately useful to unblock app development.
There will need to be 2 more follow up PRs:
1. Its own distinct action support in protocol rules.
2. Ephemeral state keeping to handle unexpected termination and resumption.
=> Added `prune` feature

.github/workflows/document-gen.yml, .github/workflows/integrity-check.yml, .github/workflows/npm-publish-unstable.yml, .github/workflows/npm-publish.yml
An attempt to fix these warnings when GitHub actions are run:
=> Updated GitHub action versions

json-schemas/interface-methods/protocol-rule-set.json, src/core/dwn-error.ts, src/core/protocol-authorization.ts, src/handlers/records-delete.ts, src/interfaces/protocols-configure.ts, src/interfaces/records-write.ts, src/types/protocols-types.ts, src/utils/records.ts, tests/core/protocol-authorization.spec.ts, tests/features/records-prune.spec.ts, tests/handlers/records-write.spec.ts, tests/vectors/protocol-definitions/free-for-all.json, tests/vectors/protocol-definitions/message.json
1. Added support for `prune` protocol action.
1. Renamed "ancestor chain" to "record chain" because the chain often contains not just the ancestor records, but also record in concern which leads to confusion.
1. Simplified context and implementation of `constructRecordChain()` 
1. Refactored `authorizeAgainstAllowedActions()` to make it more easily understood.
=> Added `prune` protocol action + `ProtocolAuthorization` refactoring

package-lock.json, package.json
Release `v0.3.3` which includes:
- util updates to `getAuthor` of `Record` to support both `RecordsWrite` and `RecordsDelete`
- bump dependency version for `@web5/dids` to `v1.0.2`
- Protocol rules associated with pruning records.
=> release `v0.3.3` of `dwn-sdk-js`

json-schemas/interface-methods/protocol-rule-set.json, package-lock.json, package.json, src/interfaces/records-write.ts, src/types/protocols-types.ts, src/utils/hd-key.ts, src/utils/records.ts, src/utils/secp256k1.ts, tests/utils/hd-key.spec.ts, tests/utils/secp256k1.spec.ts
1. Replaced bespoke key derivation algorithm to use RFC 5869 HKDF to align with the encryption text in DWN spec (that I wrote yesterday and merged this morning 🤣)
2. Other minor updates to align with the DWN spec.
3. Refactoring.
=> Replaced bespoke key derivation algorithm to use RFC 5869 HKDF

package-lock.json, package.json
- upgrade `@web5/dids` package to `v1.1.0` which allows for optionally setting `VM Key IDs`
- release `v0.3.5` of this package
=> upgrade dids package to latest v1.1.0, update release to v0.3.5

src/core/resumable-task-manager.ts
Not sure why document generator github action fails while the PR merge flow and local machine have no issue compiling:
https://github.com/TBD54566975/dwn-sdk-js/actions/runs/9473485488/job/26150552015
Regardless this should fix it.
=> Changed timer type in clearTimeoutExtensionTimer to be node.js independent

src/core/dwn-error.ts, src/core/records-grant-authorization.ts, src/protocols/permissions.ts, tests/features/permissions.spec.ts, tests/features/records-tags.spec.ts
Enforce `RecordsPermissionScope` validation on `createGrant`
=> RecordsPermissionScope Requests must be scoped to a protocol

src/core/dwn-error.ts, src/core/records-grant-authorization.ts, src/handlers/records-write.ts, src/protocols/permissions.ts, tests/features/author-delegated-grant.spec.ts, tests/features/owner-delegated-grant.spec.ts, tests/features/permissions.spec.ts, tests/handlers/protocols-query.spec.ts, tests/handlers/records-write.spec.ts
In order to get Permission Revocation messages associated with a specific protocol from the `MessageStore` it is necessary for the revocation messages to be tagged with the `protocol` from the grant scope.
In this PR:
- added an optional `protocol` property to the `PermissionRevocationCreateOptions` which normalizes and adds the provided protocol as a tag.
- added a `preProcessingForCoreRecordsWrite` method to the `RecordsWriteHandler` where if the incoming message is a revocation message, the original grant will be fetched and the protocol tag from the revocation will be compared to the grant scope protocol.
=> RecordsPermissionScope Revocation must be scoped to a protocol

src/core/message.ts, src/interfaces/records-delete.ts, src/interfaces/records-query.ts, src/interfaces/records-read.ts, src/interfaces/records-subscribe.ts, src/interfaces/records-write.ts, src/protocols/permission-grant.ts, src/protocols/permissions.ts, src/types/message-types.ts, src/types/records-types.ts, tests/interfaces/records-write.spec.ts
1. Improved typing of PermissionGrant.parse() to avoid misuse
1. Detected and fixed a couple of unimportant misuses in the tests after the above change (case in point).
=> Improved typing of PermissionGrant.parse() to avoid misuse

package-lock.json, package.json, src/index.ts, src/protocols/permission-grant.ts, src/protocols/permission-request.ts, src/protocols/permissions.ts, tests/protocols/permission-request.spec.ts
Convenience class so that a dev doesn't have to deal with a `RecordsWrite` and understand the schema directly. To be exposed in `web5-js`
=> Added convenience PermissionRequest class

src/core/message-reply.ts, src/handlers/messages-read.ts, src/types/messages-types.ts, tests/handlers/messages-read.spec.ts
- Added `entry` to `UnionMessageReply` that represents response from `MessagesRead`.
- Modified `MessagesReadReplyEntry` to include `data` as a sibling property to `message`
=> Refactor `MessagesRead` response

package-lock.json, src/dwn.ts
- Adding `did:jwk` to the default resolvers list
- Removing `did:ion` from the default resolvers list as the TBD `did:ion` gateway is no longer active
- npm audit fix elliptic ECDSA vulns. CVE-2024-42459, CVE-2024-42460, CVE-2024-42461
=> Add `did:jwk` to default resolvers, remove `did:ion`

tests/features/author-delegated-grant.spec.ts, tests/scenarios/nested-roles.spec.ts, tests/vectors/protocol-definitions/slack.json
The same test already does a nested-role authorized query on messages within a channel, but adding this to reenforce the same point.
=> Minor tweak to test to show nested-role authorized query + minor typo fixes.

.github/workflows/take.yml
This pull request introduces a new GitHub Actions workflow to automatically assign issues to contributors when they comment during the month of October. The workflow also logs when the action is skipped outside of October.
* `.github/workflows/take.yml`: Added a workflow named "Auto-assign issue to contributor" that triggers on issue comments. It includes two jobs:
* [`assign`](diffhunk://#diff-d3e004796efd8aa465cf8563e767fe5d2f555267902130b8fe4565df1bc1a77fR1-R26): Assigns the issue to the contributor if the comment is made in October.
* [`log_out_of_october`](diffhunk://#diff-d3e004796efd8aa465cf8563e767fe5d2f555267902130b8fe4565df1bc1a77fR1-R26): Logs a message indicating the action was skipped if the comment is made outside of October.
=> Hacktoberfest 2024 Add take action to auto assign contributors

src/core/dwn-error.ts, src/interfaces/protocols-configure.ts, tests/handlers/protocols-configure.spec.ts, tests/interfaces/protocols-configure.spec.ts, tests/vectors/protocol-definitions/friend-role.json, tests/vectors/protocol-definitions/slack.json, tests/vectors/protocol-definitions/thread-role.json
Currently there are some inconsistencies being able to fetch record data. If a user can only query for something, they are able to get the data if it is under the encodedData size limit, however if it is not they are unable to issue a `RecordsRead` for that record.
This change forces the user to include all 3 "read" actions (read, subscribe, query) when using any one of them in a protocol role-based action rule.
=> Enforce requiring all read actions (`read`, `query`, `subscribe`)  to exist in a protocol role rule.

src/handlers/records-read.ts, tests/handlers/records-read.spec.ts
Currently a `RecordsQuery` will return any records which you are the `author` of or `recipient` of, regardless of the protocol rules.
However `RecordsRead` would only return a record which you are the `recipient` of, and fail protocol rules for messages that you are an `author` of.
This PR more closely aligns the two by allowing a non-tenant to Read any record which they have authored regardless of the protocol rules.
=> A non-tenant `author` of a Record should be able to `RecordsRead` their record.

package-lock.json, package.json, src/handlers/records-read.ts, src/interfaces/records-delete.ts, src/interfaces/records-write.ts, src/types/records-types.ts, tests/scenarios/deleted-record.spec.ts, tests/test-suite.ts, tests/vectors/protocol-definitions/free-for-all.json
Prior to this change, a 404 status is returned without any data when a RecordsRead is performed against a deleted record.
But 404 status alone prevents a the RecordsDelete from being imported into the caller's DWN for the purpose updating the record's state.
This PR updated RecordsRead to return RecordsDelete and initial RecordsWrite when record is deleted.
=> Updated RecordsRead to return RecordsDelete and initial RecordsWrite when record is deleted

package-lock.json, package.json, src/handlers/records-read.ts, src/types/records-types.ts, tests/features/author-delegated-grant.spec.ts, tests/features/owner-signature.spec.ts, tests/features/permissions.spec.ts, tests/features/protocol-update-action.spec.ts, tests/features/records-tags.spec.ts, tests/features/resumable-tasks.spec.ts, tests/handlers/records-delete.spec.ts, tests/handlers/records-read.spec.ts, tests/handlers/records-write.spec.ts, tests/scenarios/deleted-record.spec.ts, tests/scenarios/end-to-end-tests.spec.ts, tests/scenarios/nested-roles.spec.ts
Currently the [reply structure of a `RecordsRead`](https://github.com/TBD54566975/dwn-sdk-js/blob/main/src/types/records-types.ts#L205) is quite messy: (duplicated properties, data stream nested in a message, inconsistent naming etc).
This is an attempt at cleaning it up with a flatter structure.
=> Refactored reply structure to a RecordsRead

package-lock.json, package.json, src/core/message-reply.ts, src/handlers/records-read.ts, src/index.ts, src/types/records-types.ts, tests/features/author-delegated-grant.spec.ts, tests/features/owner-signature.spec.ts, tests/features/permissions.spec.ts, tests/features/protocol-update-action.spec.ts, tests/features/records-tags.spec.ts, tests/features/resumable-tasks.spec.ts, tests/handlers/records-delete.spec.ts, tests/handlers/records-read.spec.ts, tests/handlers/records-write.spec.ts, tests/scenarios/deleted-record.spec.ts, tests/scenarios/end-to-end-tests.spec.ts, tests/scenarios/nested-roles.spec.ts
Corrected UnionMessageReply type due to changes to #817 for downstream consumption such as the `dwn-server`.
=> Corrected UnionMessageReply type for downstream consumption

tests/jose/jws/general.spec.ts
Resolves #136 
Completely covers the `ed25519.ts` file with 100% coverage.
| File Name          | Statements | Branches | Functions | Lines  |
|--------------------|------------|----------|-----------|--------|
| **Before:**        |            |          |           |        |
| All files          |   99.05    |   97.55  |   96.04   |  99.05 |
| ed25519.ts         |   93.1     |   88.88  |   83.33   |  93.1  |
| **After:**         |            |          |           |        |
| All files          |   99.09    |   97.6   |   96.25   |  99.09 |
| ed25519.ts         |   100      |   100    |   100     |  100   |
=> feat: test coverage increase in ed25519.ts

CONTRIBUTING.md, package.json, src/core/dwn-error.ts, src/handlers/records-read.ts, tests/handlers/records-read.spec.ts
=> Auth when reading deleted records

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/add-hacktoberfest-labels.yml
This PR introduces two key improvements to streamline our Hackathon process:
PR Template for Hackathon Contributors:
Added a standardized template to guide contributors in providing necessary information for their Pull Requests.
Auto-labeling GitHub Action:
Implemented an automated system to apply labels to issues. This enhancement allows us to:
Efficiently track points across repositories
Accurately count the number of contributors per PR
These changes will facilitate better organization and provide real-time insights into Hackathon participation. For an up-to-date view of participant standings, please refer to our leaderboard: https://github.com/TBD54566975/developer.tbd.website/issues/1680
=> Automating adding Hacktoberfest labels

src/dwn.ts
This PR adds the `DidWeb` method as one of the default resolvers when using a DWN.
After this PR the default resolvers will be: `DidJwk`, `DidKey`, `DidDht` and `DidWeb`
=> Add DidWeb as a default resolover method
